### ISSUE TITLE
JS SDK怎么撤回消息？

### ISSUE THREAD

**Issue by VioletCoding** [WuKongIM/WuKongIM#10]
![image](https://github.com/WuKongIM/WuKongIM/assets/37135917/2481eac8-8170-4af9-9dfb-1166740c0621)
文档写了可以通过`WKSDK.shared().chatManager`撤回消息，但是没找到对应的API，也没看到文档哪里有写。

**Comment by VioletCoding** [comment]
> 这个需要业务层支持，后续会完善这块的文档，原理就是，你业务服务器记录下已经撤回了的messageID，在线的用户就发cmd指令让他们本地删除。离线用户，拉取离线消息的时候，业务服务器组合一下这个撤回标记返回给前端。

可以稍微解释一下CMD指令吗？不是很理解这个东西，是有预设的指令在SDK里，还是说这个其实就是一个普通的字符串，里面想存什么都可以，前后端业务系统自己约定就可以了？

**Comment by tangtaoit** [comment]
是一条syncOnce=1的消息，消息内容，(type=99)你们完全可以自定义（想存什么都可以），你们服务端和客户端协商好就行。可以参考我们建议的一些定义：https://githubim.com/guide/proto.html#%E5%91%BD%E4%BB%A4%E6%B6%88%E6%81%AF

**Comment by VioletCoding** [comment]
明白了，感谢。
