### ISSUE TITLE
一些其他的问题

### ISSUE THREAD

**Issue by doralines** [WuKongIM/WuKongIM#100]
按照我之前使用一些其他开源IM的经验提出的问题

**Comment by doralines** [comment]
关于频道属性 频道属性的变更是不是也是一条消息？假设频道开启了禁言，这个时候如果用户离线，那么最近会话将这条变更消息顶掉了，用户上线后是否就无法收到禁言通知 或者 错过这个状态变更？

**Comment by tangtaoit** [comment]
> 关于频道属性 频道属性的变更是不是也是一条消息？假设频道开启了禁言，这个时候如果用户离线，那么最近会话将这条变更消息顶掉了，用户上线后是否就无法收到禁言通知 或者 错过这个状态变更？

1. 这种情况应该发cmd消息，cmd消息是写扩散，不存在顶掉的问题。

2. 像这种不建议消息里携带数据去变更客户端的数据，因为这样很难保证数据一致。

参考唐僧叨叨的操作，这种像“禁言”这个是频道的属性，也就是频道的信息，如果频道信息发送变化，服务器应该发送一条 xxx频道发生变化的cmd消息，客户端收到这条消息，应该去服务器同步频道信息，而不是根据消息的内容进行变更。
