### ISSUE TITLE
数据节点

### ISSUE THREAD

**Issue by doralines** [WuKongIM/WuKongIM#101]
我们有国外的业务，是否支持全球加速？（服务器在国外，但是在韩国、日本、中国多地都有服务器，怎么保证地区的用户优先访问到网络最佳的节点）

当然在不使用分布式的情况，能否通过中转节点提高用户的体验。

**Comment by tangtaoit** [comment]
在韩国、日本、中国部署nginx，nginx转发到WuKongIM，然后客户端连接最近的nginx （理论上应该可以，但是我们没这样试过）
