### ISSUE TITLE
悟空IM如果发生重启或者宕机可能会产生那些后果

### ISSUE THREAD

**Issue by doralines** [WuKongIM/WuKongIM#102]
这只是一个假设哈，因为看到是零依赖，所以想问一下 如果运行中的悟空IM如果发生重启和宕机，可能会产生哪些影响，维护的开发人员又应该如何处理呢？

**Comment by tangtaoit** [comment]
重启如果很快的话，用户很难感觉到，因为sdk有重连机制，会立马连接上。

宕机的话 这个只能重新启动了？

（定时备份好，wukongim的data目录）
