### ISSUE TITLE
关于服务器的部署问题

### ISSUE THREAD

**Issue by doralines** [WuKongIM/WuKongIM#103]
1.如果在liunx上部署，是否需要修改服务器openFiles之类的设置？如果需要，那么推荐设置是怎么样的规则
2.关于消息推送，我暂时还没有看到这块逻辑，所以我先问一下，会不会出现用户端，消息成堆成堆的出现，没有那种丝滑感，而不是来一条立即分发一条。

**Comment by tangtaoit** [comment]
1. openFiles这个尽量开大点嘛，这个没啥好说的。
2. 消息推送你可以看下webhook相关资料，WuKongIM会把离线消息通过webhook推送给你的业务服务器，至于你业务服务器怎么通过厂商的api推送给用户手机上 WuKongIM不关心。消息是否成堆就要看你业务服务器的处理能力了

**Comment by doralines** [comment]
> 1. openFiles这个尽量开大点嘛，这个没啥好说的。
> 2. 消息推送你可以看下webhook相关资料，WuKongIM会把离线消息通过webhook推送给你的业务服务器，至于你业务服务器怎么通过厂商的api推送给用户手机上 WuKongIM不关心。消息是否成堆就要看你业务服务器的处理能力了

我们实际的场景可能是几万在线用户，几十个超3000人的群，活跃用户8000左右，这样的话服务器应该怎么选择。

**Comment by doralines** [comment]
> 1. openFiles这个尽量开大点嘛，这个没啥好说的。
> 2. 消息推送你可以看下webhook相关资料，WuKongIM会把离线消息通过webhook推送给你的业务服务器，至于你业务服务器怎么通过厂商的api推送给用户手机上 WuKongIM不关心。消息是否成堆就要看你业务服务器的处理能力了

或者是怎么进行测试 模拟几千人同时在线发消息 我作为观察者。

**Comment by tangtaoit** [comment]
> > 1. openFiles这个尽量开大点嘛，这个没啥好说的。
> > 2. 消息推送你可以看下webhook相关资料，WuKongIM会把离线消息通过webhook推送给你的业务服务器，至于你业务服务器怎么通过厂商的api推送给用户手机上 WuKongIM不关心。消息是否成堆就要看你业务服务器的处理能力了
> 
> 我们实际的场景可能是几万在线用户，几十个超3000人的群，活跃用户8000左右，这样的话服务器应该怎么选择。

这种不算很大量，可以先上个8核16G的服务器运行。

**Comment by tangtaoit** [comment]
> > 1. openFiles这个尽量开大点嘛，这个没啥好说的。
> > 2. 消息推送你可以看下webhook相关资料，WuKongIM会把离线消息通过webhook推送给你的业务服务器，至于你业务服务器怎么通过厂商的api推送给用户手机上 WuKongIM不关心。消息是否成堆就要看你业务服务器的处理能力了
> 
> 或者是怎么进行测试 模拟几千人同时在线发消息 我作为观察者。

其实现在的IM 同时在线已经都不是问题，随便优化下 就可以做到百万同时在线，IM是否优秀还是要看消息并发，比如1秒钟服务器能处理多少消息的能力，我们测试下来 1秒钟WuKongIM可以处理大概20万左右吧（包括落盘和服务器回应客户端）

可以自己测试下，测试工具：https://githubim.com/guide/stress.html

**Comment by doralines** [comment]
> > > 1. openFiles这个尽量开大点嘛，这个没啥好说的。
> > > 2. 消息推送你可以看下webhook相关资料，WuKongIM会把离线消息通过webhook推送给你的业务服务器，至于你业务服务器怎么通过厂商的api推送给用户手机上 WuKongIM不关心。消息是否成堆就要看你业务服务器的处理能力了
> > 
> > 
> > 或者是怎么进行测试 模拟几千人同时在线发消息 我作为观察者。
> 
> 其实现在的IM 同时在线已经都不是问题（10个用户，每个用户每秒发1000条消息，跟1万个用户每个用户每秒发1条消息，其实差别不会很大），随便优化下 就可以做到百万同时在线，IM是否优秀还是要看消息并发，比如1秒钟服务器能处理多少消息的能力，我们测试下来 1秒钟WuKongIM可以处理大概20万左右吧（包括落盘和服务器回应客户端）
> 
> 可以自己测试下，测试工具：https://githubim.com/guide/stress.html

这个处理20万左右是指 一秒发送20万条并且成功分发给群内吗？

**Comment by tangtaoit** [comment]
> > > > 1. openFiles这个尽量开大点嘛，这个没啥好说的。
> > > > 2. 消息推送你可以看下webhook相关资料，WuKongIM会把离线消息通过webhook推送给你的业务服务器，至于你业务服务器怎么通过厂商的api推送给用户手机上 WuKongIM不关心。消息是否成堆就要看你业务服务器的处理能力了
> > > 
> > > 
> > > 或者是怎么进行测试 模拟几千人同时在线发消息 我作为观察者。
> > 
> > 
> > 其实现在的IM 同时在线已经都不是问题（10个用户，每个用户每秒发1000条消息，跟1万个用户每个用户每秒发1条消息，其实差别不会很大），随便优化下 就可以做到百万同时在线，IM是否优秀还是要看消息并发，比如1秒钟服务器能处理多少消息的能力，我们测试下来 1秒钟WuKongIM可以处理大概20万左右吧（包括落盘和服务器回应客户端）
> > 可以自己测试下，测试工具：https://githubim.com/guide/stress.html
> 
> 这个处理20万左右是指 一秒发送20万条并且成功分发给群内吗？

不是，指服务器确定收到了并保存后 回应成功给客户端了，这个操作完成了这条消息就算成功了（这丢消息是不可能丢了）

**Comment by doralines** [comment]
> > > > > 1. openFiles这个尽量开大点嘛，这个没啥好说的。
> > > > > 2. 消息推送你可以看下webhook相关资料，WuKongIM会把离线消息通过webhook推送给你的业务服务器，至于你业务服务器怎么通过厂商的api推送给用户手机上 WuKongIM不关心。消息是否成堆就要看你业务服务器的处理能力了
> > > > 
> > > > 
> > > > 或者是怎么进行测试 模拟几千人同时在线发消息 我作为观察者。
> > > 
> > > 
> > > 其实现在的IM 同时在线已经都不是问题（10个用户，每个用户每秒发1000条消息，跟1万个用户每个用户每秒发1条消息，其实差别不会很大），随便优化下 就可以做到百万同时在线，IM是否优秀还是要看消息并发，比如1秒钟服务器能处理多少消息的能力，我们测试下来 1秒钟WuKongIM可以处理大概20万左右吧（包括落盘和服务器回应客户端）
> > > 可以自己测试下，测试工具：https://githubim.com/guide/stress.html
> > 
> > 
> > 这个处理20万左右是指 一秒发送20万条并且成功分发给群内吗？
> 
> 不是，指服务器确定收到了并保存后 回应成功给客户端了，这个操作完成了这条消息就算成功了（这丢消息是不可能丢了）

还是没太懂，可以举个例吗？相当于是20个群，每个群里1W人，假设1W人都在线，每个群各有一条消息并全部分发给他们了，是这样的20W条吗

**Comment by tangtaoit** [comment]
> > > > > > 1. openFiles这个尽量开大点嘛，这个没啥好说的。
> > > > > > 2. 消息推送你可以看下webhook相关资料，WuKongIM会把离线消息通过webhook推送给你的业务服务器，至于你业务服务器怎么通过厂商的api推送给用户手机上 WuKongIM不关心。消息是否成堆就要看你业务服务器的处理能力了
> > > > > 
> > > > > 
> > > > > 或者是怎么进行测试 模拟几千人同时在线发消息 我作为观察者。
> > > > 
> > > > 
> > > > 其实现在的IM 同时在线已经都不是问题（10个用户，每个用户每秒发1000条消息，跟1万个用户每个用户每秒发1条消息，其实差别不会很大），随便优化下 就可以做到百万同时在线，IM是否优秀还是要看消息并发，比如1秒钟服务器能处理多少消息的能力，我们测试下来 1秒钟WuKongIM可以处理大概20万左右吧（包括落盘和服务器回应客户端）
> > > > 可以自己测试下，测试工具：https://githubim.com/guide/stress.html
> > > 
> > > 
> > > 这个处理20万左右是指 一秒发送20万条并且成功分发给群内吗？
> > 
> > 
> > 不是，指服务器确定收到了并保存后 回应成功给客户端了，这个操作完成了这条消息就算成功了（这丢消息是不可能丢了）
> 
> 还是没太懂，可以举个例吗？相当于是20个群，每个群里1W人，假设1W人都在线，每个群各有一条消息并全部分发给他们了，是这样的20W条吗

不是同时接受的并发量，是同时发送，比如1w个人 同时每秒向服务器发送20条消息。并且1w发送者的发送状态都是成功状态。至于对方有没有收到，那是接受并发测试了，这个暂时没测。IM的主要瓶颈还是在消息存储能力，发送的并发取决于消息存储能力，你说的服务器投递给用户 那是另外一个支线了，而且一般不会成为瓶颈（就算有瓶颈也在带宽，因为消息投递不涉及到db操作）
