### ISSUE TITLE
超大群 维护最近会话的问题

### ISSUE THREAD

**Issue by doralines** [WuKongIM/WuKongIM#104]
我看到你在一条回答中说到：大群跟普通群唯一的区别是，服务端不维护每个用户大群的最近会话（客户端维护）
我想问一下 这里客户端维护具体的表现是什么样的？比如用户上线后 需要客户端去额外的做什么操作吗？

在 创建或更新频道 这个api中有一个large这个参数，是否我可以在成员<XX个的时候 设置为0，当成员>XX个的时，再修改为1，这样在一个频道来回修改可以吗

**Comment by tangtaoit** [comment]
客户端不需要什么格外操作。超大群的会话 如果客户端卸载了，重新安装后会看不到 除非这个群有新消息。
