### ISSUE TITLE
调用api删除频道后 仍然可以在频道内发消息 订阅者也可以正常收到消息

### ISSUE THREAD

**Issue by doralines** [WuKongIM/WuKongIM#106]
1.先调用创建频道 然后添加了订阅者
2.调用删除频道 然后客户端发消息，仍然可以正常发送消息 订阅者也可以正常收到消息。

**Comment by tangtaoit** [comment]
建议使用禁用频道达到需求

**Comment by doralines** [comment]
没有在官网上看到这个文档

**Comment by tangtaoit** [comment]
https://githubim.com/api/channel.html

<img width="793" alt="image" src="https://github.com/WuKongIM/WuKongIM/assets/3895878/5bdb26f8-1ac7-4761-8f88-280b7b152a87">
