### ISSUE TITLE
关于群聊频道权限的问题

### ISSUE THREAD

**Issue by doralines** [WuKongIM/WuKongIM#107]
1.如果我只是创建了一个群聊频道，然后添加了一些订阅者的情况下，未在订阅名单里面的用户是否可以在频道成功发送消息？
2.如果1问题是可以的话，那么是不是在添加订阅者的同时也要添加白名单才行 如果白名单里面的个数过多 会消耗性能吗？

**Comment by tangtaoit** [comment]
未在订阅者列表里是不能发消息的 系统账号除外
