### ISSUE TITLE
白名单的问题

### ISSUE THREAD

**Issue by doralines** [WuKongIM/WuKongIM#108]
我最近在开发好友这块的功能发现一个白名单的问题
1.我想要的是 只允许和好友聊天，然后我在用户注册成功后 whitelist_add 了一个系统账号进去 用作默认的一个白名单，这样按道理来说其他用户就不能给我发消息了
2.我添加好友成功后 调用了 whitelist_add 添加该用户到我的白名单。
3.然后我删除好友 调用 whitelist_remove 把这个好友移出去了
然后我在前端发消息 发现两个好友之间仍然可以发消息，并且可以正常接收，这是什么原因？是我对这个白名单的理解有误吗

**Comment by tangtaoit** [comment]
这个bug最新代码有修复 等待发版

**Comment by doralines** [comment]
大概什么时候会发版 我方便调试我这边的代码

**Comment by tangtaoit** [comment]
> 大概什么时候会发版 我方便调试我这边的代码

周一（2024-03-04）

**Comment by doralines** [comment]
是不是我也可以直接下载git的最新代码 然后自己搭建环境部署

**Comment by tangtaoit** [comment]
> 是不是我也可以直接下载git的最新代码 然后自己搭建环境部署

可以的
