### ISSUE TITLE
Api调用步骤

### ISSUE THREAD

**Issue by functionName** [WuKongIM/WuKongIM#112]
最近在使用java实现业务服务，想问一下对应的api调用步骤是不是这样
实现目标：只允许跟好友聊天

1.添加好友
 1)向A白名单中添加B的记录 channel/whitelist_add
 2)向B白名单中添加A的记录 channel/whitelist_add

2.删除(双向)好友
 1)从A白名单中删除B  channel/whitelist_remove
 2)从B白名单中删除A  channel/whitelist_remove

3.拉黑好友
 1)添加黑名单 channel/blacklist_add

4.移除拉黑
 1)移除黑名单 channel/blacklist_remove

实现目标：群组管理
1.创建群组
 1)创建频道 channel

2.解散群组
 1)更新频道(封禁) channel

3.添加群成员
 1)添加订阅者 channel/subscriber_add

4.移除群成员 群成员退群
 1)移除订阅者 channel/subscriber_remove

5.单个群成员禁言
 1)添加黑名单 channel/blacklist_add

6.解除单个群成员禁言
 1)移除黑名单 channel/blacklist_remove

7.全员禁言
 1)设置白名单 channel/whitelist_set uid传入管理员列表 如果期间有新增管理员 就添加白名单 channel/whitelist_add

8.解除群成员禁言
 1)设置白名单 uid传入一个空数组

**Comment by tangtaoit** [comment]
理解的非常透彻👍，就是这样的。

**Comment by rowstop** [comment]
666
