### ISSUE TITLE
It seems that version 1.2.1 has been released. Could you update the image for the v1.2.1 tag to the Docker Hub

### ISSUE THREAD

**Issue by OPGithub** [WuKongIM/WuKongIM#113]
似乎1.2.1已经发布，您方便更新一下v1.2.1 tag的镜像到docker的中央仓库么

It seems that version 1.2.1 has been released. Could you update the image for the v1.2.1 tag to the Docker Hub?

**Comment by tangtaoit** [comment]
1.2.xx 的 都是这个地址： registry.cn-shanghai.aliyuncs.com/wukongim/wukongim:v1.2

**Comment by OPGithub** [comment]
https://hub.docker.com/r/wukongim/wukongim/tags 这里只能看到latest ，而这个latest是经常变的。没办法配合js sdk之类的sdk进行固定版本，也不方便排查问题。所以建议对不同正式版用不同的tag，方便拉取。

On the page https://hub.docker.com/r/wukongim/wukongim/tags, you can only see the "latest" tag, which changes frequently. This makes it difficult to work with fixed versions of JS SDKs or other SDKs, and it's also inconvenient for troubleshooting. Therefore, it is recommended to use different tags for different official releases to facilitate pulling.

**Comment by tangtaoit** [comment]
感谢建议，已经上传 v1.2.1的镜像， wukongim wukongim/wukongim:v1.2.1
