### ISSUE TITLE
用户在线状态更新流程

### ISSUE THREAD

**Issue by jkguo-looker** [WuKongIM/WuKongIM#114]

**Comment by tangtaoit** [comment]
建议流程如下：

1. 业务端通过Webhook监听到用户的在线状态后，存入或更新数据库。

2. 业务端应该定时调用WuKongIM的在线状态查询接口，查询数据库里的用户是否真正在线（如果不做这一步，WuKongIM重启，业务端是不会收到用户Webhook的在线通知的。）

3. 客户端应该调用业务服务端自己的在线状态接口，接口获取自己存入数据库的用户状态数据。

**Comment by tangtaoit** [comment]
> 【定时调用在线接口查询在线用户是否正在在线】建议定时多久同步一次在线用户状态？

此issue已关闭，请新开issue
