### ISSUE TITLE
【一分钟部署】流程遇到的问题

### ISSUE THREAD

**Issue by wengqianshan** [WuKongIM/WuKongIM#115]
1. 没有配公网 IP 的时候访问监控后台，由于无法连接 ws 服务，页面一直停留在输入 manager token状态，建议在配置文件中`monitor`标注需要依赖 ws 服务
2. 开启了 wss 服务但是没有配置证书导致下面的报错
```
panic: runtime error: invalid memory address or nil pointer dereference
```
建议在配置文件中`wssAddr`标注配置证书才可使用

**Comment by tangtaoit** [comment]
感谢，收到。
