### ISSUE TITLE
一些理解问题: warmEntries;自定义消息;用户自己的消息队列; 客户端消息保续; messageID; 去重; 纠错; keylock

### ISSUE THREAD

**Issue by Administration-LGL** [WuKongIM/WuKongIM#116]
1. warmEntries：我读代码，当索引条数 > 1024 时，会优先在最后1024条索引进行二分查找，没找到再对前面的索引进行二分查找，这里是把索引文件的后1024条索引当成热点查询吗。
2. 支持自定义消息: 对payload部分自行定义编解码规则，im只负责存储和传输。对吗
3. 每个用户有自己的一个消息队列，用户订阅了的频道的消息，我读代码，说的是(需要持久化&&只同步一次)的消息，会写到自己的这个队列。有在用这个消息队列进行消息同步吗，哪些消息是用这个队列呢
4. 客户端的消息保续是根据哪个来的，是根据每个channel/topic递增的，在持久化时，赋予的messageSeq吗
5. 服务端给每个消息生成的messageID有什么作用
6. 服务端有消息去重吗，客户端有发送消息重试，会出现服务端已经存储了消息，但是客户端没收到sendAck，导致客户端重试，然后服务端再次存储吗
7. 客户端消息去重是根据哪个字段，服务端生成的messageID吗
8. 当存储文件出错时，我读代码是对log文件进行truncate，但是似乎没有对索引文件进行对应的truncate，这个有影响吗
9.  keylock在悟空IM中的作用是啥，我看到用到的地方，都是给topicStr加锁，但是感觉这个锁加不加都没啥影响

**Comment by tangtaoit** [comment]
1. warmEntries：我读代码，当索引条数 > 1024 时，会优先在最后1024条索引进行二分查找，没找到再对前面的索引进行二分查找，这里是把索引文件的后1024条索引当成热点查询吗。

回复： 是的

2. 支持自定义消息: 对payload部分自行定义编解码规则，im只负责存储和传输。对吗

回复：对的，IM不要求payload的内容格式，payload的格式是第三方定义，这样就可以随便定义消息格式

3. 每个用户有自己的一个消息队列，用户订阅了的频道的消息，我读代码，说的是(需要持久化&&只同步一次)的消息，会写到自己的这个队列。有在用这个消息队列进行消息同步吗，哪些消息是用这个队列呢

回答：syncOnce==1表示写扩散消息是存储用户，比如命令类消息，比如好友头像更新，好友请求，群成员同步等等这种不需要显示在聊天界面的消息。

4. 客户端的消息保续是根据哪个来的，是根据每个channel/topic递增的，在持久化时，赋予的messageSeq吗

回答： 是的

5. 服务端给每个消息生成的messageID有什么作用

回答：messageID是服务端给予每个消息的唯一ID，通过这个id能够精准定位到指定消息，业务端也需要用messageID与业务数据做关联

6. 服务端有消息去重吗，客户端有发送消息重试，会出现服务端已经存储了消息，但是客户端没收到sendAck，导致客户端重试，然后服务端再次存储吗

回答：这种情况服务端确实会存储多次，当不会影响客户端的消息展示，因为重试的消息clientMsgNo是相同的，客户端有估计clientMsgNo去重的机制，所以服务端就算存储了多次，客户端也只会展示一次。

7. 客户端消息去重是根据哪个字段，服务端生成的messageID吗

回答： clientMsgNo

8. 当存储文件出错时，我读代码是对log文件进行truncate，但是似乎没有对索引文件进行对应的truncate，这个有影响吗

回答：你是对的，索引文件应该也需要truncate

9. keylock在悟空IM中的作用是啥，我看到用到的地方，都是给topicStr加锁，但是感觉这个锁加不加都没啥影响

回答：keylock是工具key进行加锁的，比如频道ch1 和频道ch2同时请求，他们是不会出现竞争锁的情况的 因为他们的key不同，只有ch1同时多个请求 才会竞争，如果不是keylock锁，ch1和ch2的请求都会竞争锁。
