### ISSUE TITLE
JS的SDK类型定义不对

### ISSUE THREAD

**Issue by VioletCoding** [WuKongIM/WuKongIM#12]
![image](https://github.com/WuKongIM/WuKongIM/assets/37135917/25836b47-ab41-47b6-b2f3-6a82c3067ef6)

如图所示ts类型定义的是Message，而实际返回的是这个：
![image](https://github.com/WuKongIM/WuKongIM/assets/37135917/73d1ea6f-8093-4c6f-94eb-e27cd836c8c8)

其中content字段的类型跟实际返回的类型对不上，导致取值时undefined。SDK定义的是：
![image](https://github.com/WuKongIM/WuKongIM/assets/37135917/329f42c5-ff9f-4e1b-b910-87d65a40fd27)

```typescript
export declare class MessageContent {
    private _contentType;
    get contentType(): number;
    set contentType(value: number);
    private _conversationDigest;
    get conversationDigest(): string;
    set conversationDigest(value: string);
    private visibles?;
    private invisibles?;
    reply: Reply;
    mention?: Mention;
    contentObj: any;
    encode(): Uint8Array;
    decode(data: Uint8Array): void;
    isVisiable(uid: string): boolean;
    decodeJSON(content: any): void;
    encodeJSON(): any;
}
```

**Comment by tangtaoit** [comment]
1. 第一个问题 其实Message2就是Message，我不知道为什么Vue里debug显示的是Message2。
2. 第二个问题取值时undefined是什么意思？ 我看你提供的图是MessageText2（也就是MessageText）MessageText继承了MessageContent，所以类型是对的

（具体参考提供的vue的demo）

**Comment by VioletCoding** [comment]
> 1. 第一个问题 其实Message2就是Message，我不知道为什么Vue里debug显示的是Message2。
> 2. 第二个问题取值时undefined是什么意思？ 我看你提供的图是MessageText2（也就是MessageText）MessageText继承了MessageContent，所以类型是对的
> 
> （具体参考提供的vue的demo）

上述是React。
chatManager的send方法返回的Message类型里的content字段，在SDK里定义的是MessageContent这个类型，而MessageContent这个类里面只有contentObj，但实际send方法返回的res里面没有contentObj这个字段，只有`content`字段，所以当你这么取值时就会undefined: `res.contentObj.xxx`，取值需要改成`res.content.xxx`。

**Comment by tangtaoit** [comment]
MessageContent是父类 看自定义消息就知道了 https://githubim.com/sdk/javascript.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%99%AE%E9%80%9A%E6%B6%88%E6%81%AF MessageText是内置的文本消息 继承的MessageContent，你可以把content转换为对应的消息对象，比如文本就是 (content as MessageText).content 这样就能获取到消息内容。

**Comment by VioletCoding** [comment]
> MessageContent是父类 看自定义消息就知道了 https://githubim.com/sdk/javascript.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%99%AE%E9%80%9A%E6%B6%88%E6%81%AF MessageText是内置的文本消息 继承的MessageContent，你可以把content转换为对应的消息对象，比如文本就是 (content as MessageText).content 这样就能获取到消息内容。

明白了
