### ISSUE TITLE
getChannelInfo 没调取回调！

### ISSUE THREAD

**Issue by fousr** [WuKongIM/WuKongIM#131]
![0bf66758e3c020adace120aec5bac86](https://github.com/WuKongIM/WuKongIM/assets/31308103/f6b809c7-3da5-45e4-96b0-60b847f5bf22)
![9ed1572130f0d721277c1b62a5eee8f](https://github.com/WuKongIM/WuKongIM/assets/31308103/ab05db32-8d8c-4f4f-ad8c-345a1764df43)
第一次使用getChannelInfo 没有调取回调，后调用的fetchChannelInfo 获取到了信息但是怎么给到变量？

**Comment by tangtaoit** [comment]
看下这个issue： https://github.com/WuKongIM/WuKongIM/issues/21

调用fetchChannelInfo 必定会触发监听 `WKSDK.shared().channelManager.addListener`

在这个监听里赋值给变量，然后刷新UI

参考代码： https://github.com/WuKongIM/WuKongIM/blob/main/demo/chatdemo/src/components/Conversation/index.vue
