### ISSUE TITLE
如何实现撤回消息功能，撤回消息功能实现思路是怎么样的

### ISSUE THREAD

**Issue by dengdengdeng** [WuKongIM/WuKongIM#136]

**Comment by tangtaoit** [comment]
1. 当客户端撤回的时候需要调用你们业务端接口，记录下撤回的消息message_id
2. 发送cmd给客户端，客户端执行cmd进行消息撤回
3. 客户端查询消息的时候，业务端从im获取到消息列表后，需要结合你本地撤回的message_id，将已撤回的消息标记为已撤回（为了安全可以抹掉payload字段）

**Comment by dengdengdeng** [comment]
1、新增撤回消息接口，存储channel_id、channel_type、message_id(client_msg_no二选一)。
