### ISSUE TITLE
我向服务器注册了一个用户，带token，  再在前端ws连接服务器，发送了token，可是后端服务器日志，提示expectToken 为空

### ISSUE THREAD

**Issue by xionglihong** [WuKongIM/WuKongIM#138]
![5a299d4034c29383152b3417f096a0c](https://github.com/WuKongIM/WuKongIM/assets/50993023/842b880e-8f92-41d9-bbae-740ba3459600)
![94b5ad21f3cad80f48f5bd9b128bc6a](https://github.com/WuKongIM/WuKongIM/assets/50993023/9b0e41f9-a048-407a-b26b-933b8b8f4337)
![2640bb3072a54fda8055578e99cc326](https://github.com/WuKongIM/WuKongIM/assets/50993023/21f8a38b-194b-4a02-8de8-fa7751a209d2)
 我向服务器注册了一个用户，带token，  再在前端ws连接服务器，发送了token，可是后端服务器日志，提示expectToken 为空
![24616567ad040f505eb9dbf0c57995b](https://github.com/WuKongIM/WuKongIM/assets/50993023/261b26d6-9466-41ca-a8d9-1f6e0f93c5ff)

**Comment by tangtaoit** [comment]
device_flag不一致导致的，jssdk默认device_flag为1，看日志你通过接口调用传的device_flag为0，所以导致token错误。

解决方案：

调用 /user/token接口的时候device_flag传1

**Comment by xionglihong** [comment]
收到 谢谢
