### ISSUE TITLE
微信小程序中wksdk不触发监听

### ISSUE THREAD

**Issue by zhoufanglu** [WuKongIM/WuKongIM#139]
<img width="783" alt="image" src="https://github.com/WuKongIM/WuKongIM/assets/24451091/3733ce42-2977-42ca-aa93-9056a5b6616c">  

并不会出发`23`这个标记log

**Comment by tangtaoit** [comment]
你试下sdk源码里的example，是否会触发。

1. 如果触发，检查你的代码与example有什么不同。
2. 如果不触发，提供下example的console控制台的错误信息。
