### ISSUE TITLE
同步最近会话时没同步群会话

### ISSUE THREAD

**Issue by huioff** [WuKongIM/WuKongIM#141]
个人频道最近会话登录就能同步到，群聊不会同步，需要在群里发个信息才能同步到最新消息？ 是BUG还是超大群问题？“注意：超大群不会维护最近会话数据。”不维护是指这个情况嘛？

**Comment by tangtaoit** [comment]
如果是超大群同步会话的时候需要传超大群的参数
<img width="860" alt="image" src="https://github.com/WuKongIM/WuKongIM/assets/3895878/62a996b3-f9aa-4efe-8bca-df390ba925bd">

https://github.com/WuKongIM/WuKongIM/blob/main/internal/server/api_conversation.go#L178

**Comment by tangtaoit** [comment]
- [ ]
