### ISSUE TITLE
不关闭白名单；不能像 系统用户发送消息

### ISSUE THREAD

**Issue by colbort** [WuKongIM/WuKongIM#144]
是否关闭个人白名单
whitelistOffOfPerson: false

错误提示如下：
2024-06-03 11:43:03 ERR msg=【Processor】not allow send message fromUID=89e533f6acfa4ed085323854da41ce70 to=u_10000 reason=ReasonNotInWhitelist

**Comment by tangtaoit** [comment]
需要将系统账号加入到WuKongIM系统账号里，你们业务服务端需要调用 https://githubim.com/api/user.html#%E6%B7%BB%E5%8A%A0%E7%B3%BB%E7%BB%9F%E8%B4%A6%E5%8F%B7

**Comment by colbort** [comment]
这个不是 唐生叨叨 在创建用户的时候就 将 系统账号拉入到 WuKongIM系统账号里 了吗

**Comment by tangtaoit** [comment]
> 这个不是 唐生叨叨 在创建用户的时候就 将 系统账号拉入到 WuKongIM系统账号里 了吗



> 这个不是 唐生叨叨 在创建用户的时候就 将 系统账号拉入到 WuKongIM系统账号里 了吗

如果你用的唐僧叨叨的代码，那么就不需要管，唐僧叨叨会自动处理
