### ISSUE TITLE
web端怎么对自定义消息进行同步编辑

### ISSUE THREAD

**Issue by wlh928043590** [WuKongIM/WuKongIM#145]
发送一条自定义消息后，实现操作比如同意拒绝后 可以编辑这条信息的状态 同步到这条自定义消息里 怎么对自定义消息进行同步编辑？

**Comment by tangtaoit** [comment]
提供一个思路：

你业务端应该有一个消息扩展表，表里有messageId和扩展内容，你同意后,扩展内容里应该有同意的标记，然后发送cmd通知客户端同步扩展内容，sdk里消息有个扩展字段，将你服务器的扩展字段保存到sdk的扩展字段内，然后UI层取这个扩展字段的内容，决定UI展示方式。
