### ISSUE TITLE
使用api调用/message/send 这个接口，SDK会保存吗？

### ISSUE THREAD

**Issue by LuciferWZX** [WuKongIM/WuKongIM#146]
![image](https://github.com/WuKongIM/WuKongIM/assets/33945463/891b5c80-82d8-4279-bd91-257469791c79)
这边我使用api的方式虽然成功的发送了消息，但是我刷新之后获取消息列表但是数据没有，只有通过WKSDK.shared().chatManager.send(inviteContent, channel) 这种方式，SDK才会保存对吗

**Comment by LuciferWZX** [comment]
我现在想新建个群聊，然后群聊建完我想有个系统消息发出来 xx邀请了aa,bb,cc 这种，但是我这边通过api调用，刷新之后就不会出现，有啥思路或者好办法，我这边用的nestjs做的后端，消息我这边不想做保存，只想直接用sdk的，之后在考虑保存吧

**Comment by LuciferWZX** [comment]
@tangtaoit 大佬帮帮忙哈

**Comment by tangtaoit** [comment]
sync_once设置为0，1表示是命令消息，命令消息不会显示在会话里
