### ISSUE TITLE
这个消息发送状态监听报错误3会是什么问题呢

### ISSUE THREAD

**Issue by tiziyt** [WuKongIM/WuKongIM#148]
![微信图片_20240705121223](https://github.com/WuKongIM/WuKongIM/assets/101624234/42cd9f0e-f76e-4be9-83ad-e24caed2b271)

**Comment by tangtaoit** [comment]
https://github.com/WuKongIM/WuKongIMGoProto/blob/main/common.go#L157

发送者没在频道内。

**Comment by tiziyt** [comment]
会是哪一步出错了吗 channelid是对的上的呢
