### ISSUE TITLE
邀请好友的系统消息会报错.     而且没有走WKIM.shared.messageManager.addOnRefreshMsgListener监听方法?

### ISSUE THREAD

**Issue by xiaotuoluo123** [WuKongIM/WuKongIM#149]
<img width="1422" alt="截屏2024-07-08 11 58 19" src="https://github.com/WuKongIM/WuKongIM/assets/146710480/c517ed02-3da1-43cd-a3d2-34cd860b4bd6">

**Comment by tangtaoit** [comment]
使用最新flutter版本的sdk测试
