### ISSUE TITLE
Websocket 的使用文档哪里可以看到的？

### ISSUE THREAD

**Issue by jjeejj** [WuKongIM/WuKongIM#15]
示例 的 web demo 我看是使用 websocket 发送的消息，但是没有看到这一部分的文档，在哪里可以看到的？

**Comment by tangtaoit** [comment]
websocket使用的jssdk 地址 https://githubim.com/sdk/javascript.html

**Comment by jjeejj** [comment]
服务器端不能使用 吗？

**Comment by jjeejj** [comment]
还有 请问一下，服务端接口的文档 是不是没有写完？ 现在调用登录注册后不算在线， 只有建立 socket 连接后才算在线

**Comment by tangtaoit** [comment]
你的需求是什么？

**Comment by jjeejj** [comment]
把 悟空 IM 当作一个底层服务，在写一个业务服务对接 IM 提供的能力 对 前端提供服务

**Comment by tangtaoit** [comment]
客户端要使用sdk的长连接能力发消息，长连接在才算在线，http api是给你业务后端调用的，一般发送系统类的消息或模拟某个账号发消息给客户端。不存在不在线的概念。

**Comment by jjeejj** [comment]
我看官方推荐的实践是这样的，客户的会连接 悟空 IM
![image](https://github.com/WuKongIM/WuKongIM/assets/15176971/82b6f013-c209-48ee-b49c-2e6ef5ca8342)

--------------
现在想下面这样接入，是不是实现不了？
<img width="754" alt="image" src="https://github.com/WuKongIM/WuKongIM/assets/15176971/3c0a598f-dc35-4cab-bdb2-ff1d6961b567">

**Comment by tangtaoit** [comment]
你可以业务端通过webhook事件监听客户端发的消息，然后业务端分析消息后，再通过http api 发送消息，但是客户端必须长连接到WuKongIM

**Comment by jjeejj** [comment]
> 你可以业务端通过webhook事件监听客户端发的消息，然后业务端分析消息后，再通过http api 发送消息，但是客户端必须长连接到WuKongIM

客户端必须长连接到WuKongIM,这样不满足需求了啊， 我们客户端对接的自由自己的服务端，服务端去对接 其他的第三方im 渠道

**Comment by tangtaoit** [comment]
客户端都长连接到你业务端了，你还用什么其他的第三方IM啊😂，你们这架构就有问题

**Comment by jjeejj** [comment]
也就是 现在 是不能只作为服务端提供完全的能力，必须依赖客户端连接 悟空IM 服务端 ，是这样的吗？

**Comment by tangtaoit** [comment]
是的
