### ISSUE TITLE
Javascript集成 npm i wukongimjssdk 报错

### ISSUE THREAD

**Issue by BeatingWorldline** [WuKongIM/WuKongIM#152]
![微信截图_20240717101307](https://github.com/user-attachments/assets/c6f92555-5b98-461e-80c3-50fef82d7960)

不开VPN或开VPN切换各种节点,全部报错：request to https://registry.npmjs.org/wukongimjssdk failed

无法拉取

**Comment by tangtaoit** [comment]
看错误像网络问题，你看下是否设置了npm代理？ 去掉npm代理 然后开vpn拉试试

**Comment by BeatingWorldline** [comment]
已解决
