### ISSUE TITLE
IOS移动端设备连接失败

### ISSUE THREAD

**Issue by BeatingWorldline** [WuKongIM/WuKongIM#155]
相同代码在安卓平台的浏览器中可以正常连接，但是在IOS设备的浏览器中就会失败反复重连。可能的原因是什么？如何debug？

**Comment by BeatingWorldline** [comment]
还有在哪里看日志  报错信息太简略了看不出问题

**Comment by BeatingWorldline** [comment]
![a9a338085b4a042f5bb5753fdfd4b11](https://github.com/user-attachments/assets/634d1263-740d-418a-934f-ee27529bec32)

**Comment by BeatingWorldline** [comment]
reasonCode   0  代表什么？

**Comment by tangtaoit** [comment]
你跑sdk里的那个example看有没有问题

**Comment by BeatingWorldline** [comment]
> 你跑sdk里的那个example看有没有问题

reasonCode 0 代表什么？

**Comment by tangtaoit** [comment]
> > 你跑sdk里的那个example看有没有问题
> 
> reasonCode 0 代表什么？

0表示未知错误，你那错误应该连接都还没建立成功。

**Comment by tangtaoit** [comment]
你是用的jssdk吗？

**Comment by chestnutLeaves** [comment]
> 你是用的jssdk吗？

是的

**Comment by tangtaoit** [comment]
1.你连我们的官方的地址看是否能连接成功。

2. 使用sdk里的example是否能连接成功。

**Comment by BeatingWorldline** [comment]
> 1.你连我们的官方的地址看是否能连接成功。
> 
> 2. 使用sdk里的example是否能连接成功。
在IOS浏览器内，sdk的例子和官网的都可以连接成功。只有我们自己开发部署的站点会连接失败 OTZ

**Comment by BeatingWorldline** [comment]
> 1.你连我们的官方的地址看是否能连接成功。
> 
> 2. 使用sdk里的example是否能连接成功。

已解决，原因是但在safari浏览器的安全机制下，https环境下的http请求是不被允许的，导致websocket第一次http请求意外中断。
