### ISSUE TITLE
自动回复和敏感词过滤怎么处理

### ISSUE THREAD

**Issue by OPGithub** [WuKongIM/WuKongIM#157]
目前看起来是，所有请求都要到自己服务器进行处理

**Comment by tangtaoit** [comment]
两种方式：

1. 服务端通过webhook监听到消息内容，然后审核如果有问题发送一条“删除”命名给客户端，客户端去删除。（如果审核很快的，客户端应该删除也很快，体验来说，可能有点瑕疵）

2. 客户端处理，客户端第一次启动的时候，同步敏感词库到本地，然后客户端本地匹配过滤

**Comment by thanatoswuhen** [comment]
> 两种方式：
> 
> 1. 服务端通过webhook监听到消息内容，然后审核如果有问题发送一条“删除”命名给客户端，客户端去删除。（如果审核很快的，客户端应该删除也很快，体验来说，可能有点瑕疵）
> 2. 客户端处理，客户端第一次启动的时候，同步敏感词库到本地，然后客户端本地匹配过滤

疑问：
1、能不能用第三方的审核服务，实现先审核，再发送？

**Comment by tangtaoit** [comment]
> > 两种方式：
> > 
> > 1. 服务端通过webhook监听到消息内容，然后审核如果有问题发送一条“删除”命名给客户端，客户端去删除。（如果审核很快的，客户端应该删除也很快，体验来说，可能有点瑕疵）
> > 2. 客户端处理，客户端第一次启动的时候，同步敏感词库到本地，然后客户端本地匹配过滤
> 
> 疑问： 1、能不能用第三方的审核服务，实现先审核，再发送？

目前不支持先审再发，只支持先发再审，再追回。
