### ISSUE TITLE
手动补消息

### ISSUE THREAD

**Issue by superlbr** [WuKongIM/WuKongIM#158]
不知道是server的问题，还是客户端的问题，有消息漏了，想补一下

**Comment by tangtaoit** [comment]
那个版本的WuKongIM，目前没见人反馈过这个问题，如果真发送成功了，WuKongIM自己就有自动补漏机制，可以详细描述下出现的流程吗？如果能复现那就最好了。

**Comment by superlbr** [comment]
wukongIM版本 1.25~1.26之间，某个git。
客户端是jssdk，做了适配，放在小程序上跑。
为了实现未读推送，客户端发送消息后，会上报。
问题就是消息上报了，但是wukongIM会话列表里没有。
目前是偶发，之前怀疑是小程序页面切换太快，导致消息没来得及发出去。后面上报，才发现肯定是漏了，而且没有error

**Comment by tangtaoit** [comment]
> wukongIM版本 1.25~1.26之间，某个git。 客户端是jssdk，做了适配，放在小程序上跑。 为了实现未读推送，客户端发送消息后，会上报。 问题就是消息上报了，但是wukongIM会话列表里没有。 目前是偶发，之前怀疑是小程序页面切换太快，导致消息没来得及发出去。后面上报，才发现肯定是漏了，而且没有error

客户端是确认wukongim的jssdk发送消息并成功返回ack后才上报的吗？

你应该是没在ack后上报的吧？ 只有服务器ack返回reason为成功后才表示发送成功了，否则都不算成功。

服务器的机制是只有存储成功了，才会ack成功。 只要服务器存储成功了，客户端就一定能拉到。

**Comment by superlbr** [comment]
```
    const sendRes = WKSDK.shared().chatManager.send(chatMessage, new Channel(friend.user_id, ChannelTypePerson))
    const msg = imOperator.onSimulateSendMsg({ content });
    _updateViewWhenSendSuccess(msg, itemIndex);

    const needReportObj: any = {
        user_id,
        channel_id: friend.user_id,
        content: type == 'text' ? content : content.content,
    }
    if (sendRes && sendRes.clientMsgNo) {
        needReportObj['msg_no'] = sendRes.clientMsgNo
    }
    await request('chat', 'conversationCheck', needReportObj)
```

**Comment by superlbr** [comment]
发送代码如上，调用send，然后上报。虽然chatManager.send是同步方法，但应该是先执行的，按说ws的发送应该是很快的。

**Comment by tangtaoit** [comment]
send只表示发送了， 服务器有没有收到或处理成功是未知的。

要在监听服务器回执里上报：
<img width="792" alt="image" src="https://github.com/user-attachments/assets/88fa8fd0-a05c-49a5-b492-b4f8e080f230">

packet.reasonCode === 1才表示发送成功

**Comment by superlbr** [comment]
这里发送失败，会自动重试吗

**Comment by tangtaoit** [comment]
> 这里发送失败，会自动重试吗

如果服务器返回了失败就不会重试了，因为发生错误了
