### ISSUE TITLE
请问 docker 里面部署的话  ip 在哪里设置

### ISSUE THREAD

**Issue by long0419** [WuKongIM/WuKongIM#16]
![image](https://github.com/WuKongIM/WuKongIM/assets/1064859/cb2be63b-212e-44e6-9f1d-e7bbcaee35ae)

**Comment by tangtaoit** [comment]
可以使用Docker的环境变量配置，图上的可以转换为环境变量为 WK_EXTERNAL_IP，所有配置项都可以转换为环境变量的参数，具体查看文档 https://githubim.com/guide/fullconfig.html#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F
