### ISSUE TITLE
最新版集原生群部署时，monitor.addr 配置不生效

### ISSUE THREAD

**Issue by chestnutLeaves** [WuKongIM/WuKongIM#160]
![image](https://github.com/user-attachments/assets/2aae9bb4-ccbb-487a-b91e-fc1e317d7ae7)
如图，配置文件中其他的配置都生效了，但是管理平台的好像没生效导致启动失败了。是我理解错了配置的字段吗，还是这个字段配置文件不起作用，默认5300了？

**Comment by chestnutLeaves** [comment]
![image](https://github.com/user-attachments/assets/78ed5934-80da-4bd7-a90c-22e990cb16ac)
查阅咱们项目的代码后，发现代码里用的是 "manager.addr" 修改配置后可以了。
可能文档需要更新或者是个bug

**Comment by tangtaoit** [comment]
已修复
