### ISSUE TITLE
2.0.2 版本stop命令无效

### ISSUE THREAD

**Issue by chestnutLeaves** [WuKongIM/WuKongIM#161]
![image](https://github.com/user-attachments/assets/f675bf6d-07d4-44bc-89d8-b4ae4899ca19)
现在通过stop去停止程序存在问题，不知道跟我没有将安装包放在~/wukongim有没有关系

**Comment by tangtaoit** [comment]
应该是启动没成功，所以stop报错了

**Comment by mofei999** [comment]
![image](https://github.com/user-attachments/assets/d2b30271-e15c-4822-a000-6f4056c46044)
我也遇到这种问题，启动时会提示说wukongim在守护进程中运行
