### ISSUE TITLE
linux部署的悟空im测试连接不上一直提示断开

### ISSUE THREAD

**Issue by liuenbo123** [WuKongIM/WuKongIM#17]
linux部署的 悟空im, 测试连接不上一直提示断开, 已经配置了外网IP, console显示的是内网连接 5200 端口

**Comment by tangtaoit** [comment]
检查配置是否生效 比如debug改成release 看启动日志的mode是不是release，如果不是就说明配置未生效

如果配置未生效，检查配置是不是因为缩进不对，配置是yaml格式的，层级和缩进有严格要求。

参考官方文档的配置的层级和缩进： https://githubim.com/guide/fullconfig.html

**Comment by liuenbo123** [comment]
现在可以连接了,现在有一个新问题, 移动端通过 daodaoservie连接,发送不了消息,是怎么回事啊

**Comment by tangtaoit** [comment]
另外开一个issue 贴上日志，没日志不好分析
