### ISSUE TITLE
为什么我部署之后，指定地址为本地地址，WebSocket地址一直都是127.0.0.0

### ISSUE THREAD

**Issue by mofei999** [WuKongIM/WuKongIM#171]
![1724923180950](https://github.com/user-attachments/assets/b13c7548-2a53-4681-ad4f-795adb951050)
![1724923250061](https://github.com/user-attachments/assets/b8d9195d-a6d8-4b13-b84c-23830783d882)

**Comment by mofei999** [comment]
> <img alt="图像" width="411" src="https://private-user-images.githubusercontent.com/3895878/362617148-03d6e969-b8ed-4b37-b022-e4caa98c9198.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MjM5NjksIm5iZiI6MTcyNDkyMzY2OSwicGF0aCI6Ii8zODk1ODc4LzM2MjYxNzE0OC0wM2Q2ZTk2OS1iOGVkLTRiMzctYjAyMi1lNGNhYTk4YzkxOTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMDkyNzQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Nzk3ZGUyOTUwYTJkMDUwYmZlOTE4NzcwZTg4ZDQ3NTM5YmFiMDU4NDAzNzlmOGQ1ODk0OTgwOTg4ZDZiZTFkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PMbo3STqrtTAm9-sU-w0vEESW0u7z1yfv6MgWTD7ydw">
> 这里需要配置能够访问的IP
> 
> 配置修改后记得重新启动

你的意思是在启动服务时，会加载配置文件，如果里面出现配置错误，或者有ip无法访问，服务就不会走配置文件，而是走默认

**Comment by tangtaoit** [comment]
> > <img alt="图像" width="411" src="https://private-user-images.githubusercontent.com/3895878/362617148-03d6e969-b8ed-4b37-b022-e4caa98c9198.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MjM5NjksIm5iZiI6MTcyNDkyMzY2OSwicGF0aCI6Ii8zODk1ODc4LzM2MjYxNzE0OC0wM2Q2ZTk2OS1iOGVkLTRiMzctYjAyMi1lNGNhYTk4YzkxOTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMDkyNzQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Nzk3ZGUyOTUwYTJkMDUwYmZlOTE4NzcwZTg4ZDQ3NTM5YmFiMDU4NDAzNzlmOGQ1ODk0OTgwOTg4ZDZiZTFkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PMbo3STqrtTAm9-sU-w0vEESW0u7z1yfv6MgWTD7ydw">
> > 这里需要配置能够访问的IP
> > 配置修改后记得重新启动
> 
> 你的意思是在启动服务时，会加载配置文件，如果里面出现配置错误，或者有ip无法访问，服务就不会走配置文件，而是走默认

检查你的配置文件是否生效。 比如修改mode为debug 然后启动后控制台输出是否是debug。 external.ip这个填的什么 web也就是连的填的这个ip
