### ISSUE TITLE
Acceptor和epollPoller一直报错，导致日志过大存满磁盘

### ISSUE THREAD

**Issue by xwg-github** [WuKongIM/WuKongIM#172]
日志报错信息：
{"level":"error","time":"2024-08-08 16:48:36","msg":"【Acceptor】Accept() failed","error":"too many open files"}
{"level":"error","time":"2024-08-08 16:48:36","msg":"【epollPoller[0]】error occurs in event-loop","error":"accept a new connection error"}
全是这2条报错，日志记录直至磁盘空间占满
Acceptor和epollPoller是做什么用的？如何解决这个问题？

**Comment by tangtaoit** [comment]
使用的那个版本？ 高峰并发多大

**Comment by xwg-github** [comment]
版本号我好像没看到过，5月份的git下载的。
高峰并发没监听过。目前总用户数1500+

**Comment by tangtaoit** [comment]
> 版本号我好像没看到过，5月份的git下载的。 高峰并发没监听过。目前总用户数1500+

先将代码更新到最新，如果是v1版本 使用v1分支的最新代码

**Comment by xwg-github** [comment]
1.那现在这个问题是什么情况下会触发的呢？
2.v2可以直接兼容唐僧叨叨么？

**Comment by xwg-github** [comment]
1.那现在这个问题是什么情况下会触发的呢？
2.v2可以直接兼容唐僧叨叨么？

**Comment by tangtaoit** [comment]
> 1.那现在这个问题是什么情况下会触发的呢？ 2.v2可以直接兼容唐僧叨叨么？

这个问题v1最新分支应该修复了。

v2兼容唐僧叨叨，v2目前还是beta版本。不建议上生产

**Comment by xwg-github** [comment]
好的，谢谢。之前出现这个问题悟空IM版本是v1.2.4。我先升级到1.2.6看看
