### ISSUE TITLE
问题：同步最近会话接口没有获取数量限制

### ISSUE THREAD

**Issue by Cloud-Yao** [WuKongIM/WuKongIM#173]
我在我的服务端调用下面的接口，获取最近的会话信息并返回给客户端（Web或者App）进行显示，但是这个接口调用好像没有单次获取最大会话数的限制，会不会一个用户有特别多的最近会话，那么返回的数据会特别的多，会不会出现风险？
<img width="886" alt="image" src="https://github.com/user-attachments/assets/e47cc9e5-7f5e-48f4-832c-e17d660dd9aa">

**Comment by tangtaoit** [comment]
有限制的，通过配置文件可以配置 默认是显示最新1000条。

<img width="701" alt="image" src="https://github.com/user-attachments/assets/bdb3e3a8-02cd-495e-a3e7-2e6cae4ff6c2">

**Comment by Cloud-Yao** [comment]
OK，谢谢
