### ISSUE TITLE
日志里可以显示更准确的代码位置

### ISSUE THREAD

**Issue by ian-qiu** [WuKongIM/WuKongIM#175]
{"level":"error","time":"2024-09-05 11:36:58.474","linenum":"/go/release/pkg/wklog/logger.go:154","msg":"【Server】查询最近消息失败！","error":"end messageSeq[19] must be less than start messageSeq[11]","uid":"abc","fakeChannelID":"10333@10254","channelType":1,"LastMsgSeq":20}
{"level":"error","time":"2024-09-05 11:36:58.474","linenum":"/go/release/pkg/wklog/logger.go:154","msg":"【ConversationAPI】获取最近消息失败！","error":"end messageSeq[19] must be less than start messageSeq[11]"}
{"level":"error","time":"2024-09-05 11:39:09.886","linenum":"/go/release/pkg/wklog/logger.go:154","msg":"【Server】查询最近消息失败！","error":"end messageSeq[12] must be less than start messageSeq[11]","uid":"abc","fakeChannelID":"abc@def","channelType":1,"LastMsgSeq":13}
{"level":"error","time":"2024-09-05 11:39:09.887","linenum":"/go/release/pkg/wklog/logger.go:154","msg":"【ConversationAPI】获取最近消息失败！","error":"end messageSeq[12] must be less than start messageSeq[11]"}

所有的linenum显示的位置均一致，可以设置zap的AddCallerSkip，定位到更具体的打日志的位置。

**Comment by tangtaoit** [comment]
这个是个BUG，等待修复

**Comment by tangtaoit** [comment]
已修复
