### ISSUE TITLE
发送消息后，获取到的最近会话，会出现重复冗余的会话，我们发送了多次，发现有的会出现，有的不会出现

### ISSUE THREAD

**Issue by mofei999** [WuKongIM/WuKongIM#176]
![91b9cf1cddeabf48ef47e58e55ce063](https://github.com/user-attachments/assets/6504aa75-07a7-4c46-bc62-3923b05ba43d)
![image](https://github.com/user-attachments/assets/bf28b29a-0feb-441a-bdeb-03df5131cfe6)
查看管理后台并未出现重复内容

**Comment by tangtaoit** [comment]
用的那个版本？

**Comment by mofei999** [comment]
> 用的那个版本？

2.0.1

**Comment by mofei999** [comment]
> 用的那个版本？

目前稳定的版本是哪个

**Comment by tangtaoit** [comment]
目前还在beta阶段，你说的这个问题 v2.0.3-beta-20240828 版本应该解决了
