### ISSUE TITLE
linux部署的daodaoserver连接部署悟空im, 发送不了消息

### ISSUE THREAD

**Issue by liuenbo123** [WuKongIM/WuKongIM#18]
悟空im配置已经成功了, 通过叨叨server连接悟空im 发送消息,发送不了
{"level":"debug","time":"2023-08-09 20:11:49","msg":"【Webhook】收到离线消息->","msg":{"header":{"no_persist":0,"red_dot":1,"sync_once":0},"setting":0,"client_msg_no":"c79f4c242df94a63ab4c0fa129ad14c20","message_id":1689248112654155776,"message_seq":10,"from_uid":"u_10000","to_uid":"","channel_id":"abaa7588bc624ce2a5f77d161900c91e","channel_type":1,"timestamp":1691583109,"payload":"eyJjb250ZW50Ijoi5qyi6L+O5L2/55So5Lqs5aCwXG7kuIrmrKHnmoTnmbvlvZXkv6Hmga/vvJoxMjMuMTQ5LjQ4Ljc4IDIwMjMtMDgtMDkgMTk6NTk6MDNcbuacrOasoeeZu+W9leeahOS/oeaBr++8mjEyMy4xNDkuNDguNzggMjAyMy0wOC0wOSAyMDoxMTo0OSIsInR5cGUiOjF9","ContentType":0,"PayloadMap":null,"to_uids":["abaa7588bc624ce2a5f77d161900c91e"]}}
{"level":"debug","time":"2023-08-09 20:11:49","msg":"【Webhook】开始推送","uid":"abaa7588bc624ce2a5f77d161900c91e","deviceType":"VIVO","deviceToken":"v2-CQXhgXSU9-4qtCC9_EeUr2K-HKmRilOIOinWEwfKMDrqyaCu6kQhsce4"}
{"level":"debug","time":"2023-08-09 20:11:49","msg":"【Webhook】推送失败！","uid":"abaa7588bc624ce2a5f77d161900c91e","deviceType":"VIVO","deviceToken":"v2-CQXhgXSU9-4qtCC9_EeUr2K-HKmRilOIOinWEwfKMDrqyaCu6kQhsce4","error":"不支持的推送设备！"}
{"level":"debug","time":"2023-08-09 20:11:49","msg":"【Webhook】收到webhook grpc事件","event":"msg.notify","data":"[{\"header\":{\"no_persist\":0,\"red_dot\":1,\"sync_once\":0},\"setting\":0,\"message_id\":1689248112654155776,\"message_idstr\":\"1689248112654155776\",\"client_msg_no\":\"c79f4c242df94a63ab4c0fa129ad14c20\",\"message_seq\":10,\"from_uid\":\"u_10000\",\"channel_id\":\"abaa7588bc624ce2a5f77d161900c91e\",\"channel_type\":1,\"timestamp\":1691583109,\"payload\":\"eyJjb250ZW50Ijoi5qyi6L+O5L2/55So5Lqs5aCwXG7kuIrmrKHnmoTnmbvlvZXkv6Hmga/vvJoxMjMuMTQ5LjQ4Ljc4IDIwMjMtMDgtMDkgMTk6NTk6MDNcbuacrOasoeeZu+W9leeahOS/oeaBr++8mjEyMy4xNDkuNDguNzggMjAyMy0wOC0wOSAyMDoxMTo0OSIsInR5cGUiOjF9\"}]"}
mention--robotID-->

**Comment by tangtaoit** [comment]
日志只是离线推送失败，没看出来发送消息失败

**Comment by liuenbo123** [comment]
问题找到了, 像我这种明明连接成功了,就是发消息发不过去情况 .
https://tangsengdaodao.com/dev/backend/port.html 我的处理方法是,其中有一个端口没有开,找了老半天
