### ISSUE TITLE
iOS 自定义消息，上传文件数据。

### ISSUE THREAD

**Issue by IOS-ZXX** [WuKongIM/WuKongIM#180]
我们使用WuKongIM只是用于基础的单线聊天。不用视频/语音，只是在发送一些附件信息。
如何自定义集成WKMediaMessageContent类，那些是需要自己定义写的方法？在文件上传需要遵守哪些协议呢？

**Comment by tangtaoit** [comment]
原理如下：

当调用sdk的 send方法的时候，sdk会判断是否是WKMediaMessageContent对象，如果是 则会调用注册的自定义上传任务，上传任务应该获取WKMediaMessageContent对象里的localPath属性路径对应的文件进行上传到自己的服务器上，然后将文件下载地址设置到 WKMediaMessageContent里的remoteUrl属性，上传完成后，sdk会将此消息和对应的文件下载地址发送给对方


具体流程：

1. 自定义消息继承WKMediaMessageContent，WKMediaMessageContent对象有一个关键方法`writeDataToLocalPath`和一个关键属性`localPath`
2. 重写`writeDataToLocalPath` 将你的数据写入到`localPath`这个本地路径文件内
参考语音消息：

https://github.com/WuKongIM/WuKongIMiOSSDK/blob/main/WuKongIMSDK/Classes/model/content/WKVoiceContent.m

<img width="937" alt="image" src="https://github.com/user-attachments/assets/dbd8437c-d88c-4a20-a0e7-8d23d4e7fc64">

3. 自定义上传/下载 任务

对应文档： https://githubim.com/sdk/ios.html#%E6%B6%88%E6%81%AF%E9%99%84%E4%BB%B6%E4%B8%8A%E4%BC%A0%E8%AE%BE%E7%BD%AE

参考代码： https://github.com/TangSengDaoDao/TangSengDaoDaoiOS/blob/main/Modules/WuKongDataSource/WuKongDataSource/Classes/WKFileUploadTask.m#L69

`记得注册上传任务`

<img width="756" alt="image" src="https://github.com/user-attachments/assets/ec34d82a-d0f7-42eb-9946-978f9ef8148f">

**Comment by tangtaoit** [comment]
长时间没有回复，关闭issue
