### ISSUE TITLE
集成到自己系统的新方案

### ISSUE THREAD

**Issue by Cloud-Yao** [WuKongIM/WuKongIM#181]
请教一下，我想把WukongIM集成到自己系统，但是不同于官网的方案，官方提供的方案是直接通过客户端SDK发送各种类型的消息到WukongIM Server，然后通过Webhook的方式将数据同步到自己的应用服务器。我现在计划的是先在客户端（App/Web/PC）把消息发送到自己的应用服务器，应用服务器这时候可以对这条消息做一系列处理（例如，敏感词过滤、保存到数据库等等），然后应用服务器在通过后台服务接口把消息发送到WukongIM Server，我想问一下，这样做可以吗？ 会不会有什么大问题？
（简略的流程图如下）
<img width="1181" alt="image" src="https://github.com/user-attachments/assets/9f7216cc-516a-4e91-be2c-8ba8c761fd9c">

**Comment by tangtaoit** [comment]
不推荐这样做。

1. 这样做需要修改WuKongIM的源码，让消息不投递给对方，由你服务器调用api去投递。
2. 通过api发消息性能肯定不如通过长连接发消息高。

敏感词推荐客户端处理，参考唐僧叨叨敏感词的处理过程。

**Comment by gopkg-dev** [comment]
本地处理敏感词可能导致敏感过滤词信息泄露，用户可绕过过滤，肆无忌惮地发送广告，增加管理风险。

**Comment by tangtaoit** [comment]
> 本地处理敏感词可能导致敏感过滤词信息泄露，用户可绕过过滤，肆无忌惮地发送广告，增加管理风险。

他也只能绕过自己的。
