### ISSUE TITLE
最大群聊人数和超大群的设置

### ISSUE THREAD

**Issue by Cloud-Yao** [WuKongIM/WuKongIM#182]
官网推荐在群聊超过500人的时候就设置为超大群，但是就不在维护最近会话关系。我想建一个人数比较大群，例如在1000-3000人左右的样子，但是不设置为超大群，维护最近会话，这样做会有什么风险吗？

**Comment by tangtaoit** [comment]
v1版本的话 这样做对服务器性能消耗比较大。因为一条消息要更新1000-3000个会话。

v2版本已经不分超级群和普通群了，维护会话采用读模式计算的形式，对性能大幅度提升。

**Comment by Cloud-Yao** [comment]
OK, 我看官方文档的v2版本中，后台服务接口依然保留large参数。希望可以尽快更新v2的文档内容
<img width="1487" alt="image" src="https://github.com/user-attachments/assets/5fe3739b-2d58-42d6-b173-a1913a2304fe">
另外，还想打听一下，k8s版本部署v2的文档大概什么时候上线？

**Comment by tangtaoit** [comment]
好的，感谢指出

v2的k8s脚本，要等release后，再编写，你可以加我们的官方微信群，群里问下，群里有人编写好了的。

<img width="705" alt="image" src="https://github.com/user-attachments/assets/7f42ffcb-1ae8-431f-bdd5-1524311a37fc">
