### ISSUE TITLE
认证配置信息写到哪个配置文件中

### ISSUE THREAD

**Issue by xiaomili666** [WuKongIM/WuKongIM#186]
![认证配置](https://github.com/user-attachments/assets/44a4f575-cee2-43c2-9a6a-f33ee654785c)

**Comment by tangtaoit** [comment]
这个是yaml格式的配置，docker-compose部署是采用的`environment `配置，但是WuKongIM支持所有的yaml格式的配置转换为`environment`配置，转换过程参考文档：https://githubim.com/server/config/config.html#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F

转换后就可以配置在docker-compose.yaml文件内了

类似如下：

<img width="777" alt="image" src="https://github.com/user-attachments/assets/cfc2be1a-613e-46f5-ad98-c8e4e44dbb0b">
