### ISSUE TITLE
配置WSS报错

### ISSUE THREAD

**Issue by lty19910115** [WuKongIM/WuKongIM#191]
"msg":"【Acceptor】initWSSListener() failed","error":"bind: cannot assign requested address","stacktrace":"github.com/WuKongIM/WuKongIM/pkg/wklog.Panic\n\tgithub.com/WuKongIM/WuKongIM/pkg/wklog/logger.go:157\ngithub.com/WuKongIM/WuKongIM/pkg/wklog.(*WKLog).Panic\n\tgithub.com/WuKongIM/WuKongIM/pkg/wklog/logger.go:264\ngithub.com/WuKongIM/WuKongIM/pkg/wknet.(*Acceptor).start.func3\n\tgithub.com/WuKongIM/WuKongIM/pkg/wknet/acceptor.go:88"
![1730709232612](https://github.com/user-attachments/assets/9412dacd-4bd8-4a6d-b26c-1663df93f5e8)

**Comment by tangtaoit** [comment]
最外面的那个wssAddr是监听地址 固定的 wss://0.0.0.0:5210即可
