### ISSUE TITLE
配置问题 

### ISSUE THREAD

**Issue by lty19910115** [WuKongIM/WuKongIM#192]
![1730711310709](https://github.com/user-attachments/assets/bdb368f5-8c56-480e-b013-f082f5c88343)
这个配置    jssdk  访问这个还是访问不到      WKSDK.shared().config.addr = 'wss://*****.com:5210/';

**Comment by tangtaoit** [comment]
浏览器的日志和WuKongIM的日志截图看下

**Comment by lty19910115** [comment]
{
	"action": "error",
	"message": "[object Event]",
	"time": "17:25:49",
	"Request URL": "wss://im.hainanyizhi.com:5210/",
	"Request Method": "Raw",
	"header": [],
	"id": "31c75428f88001",
	"mode": "text"
}

![image](https://github.com/user-attachments/assets/37b434af-addc-4a01-a302-a7ea36a74c32)
![image](https://github.com/user-attachments/assets/7af296f4-8654-47ca-9225-732333cef4e8)
![image](https://github.com/user-attachments/assets/fb320c27-1628-4e87-b415-cdc345a8b1b3)

**Comment by tangtaoit** [comment]
<img width="528" alt="image" src="https://github.com/user-attachments/assets/a625ae98-e3dc-42f7-9150-a319d114417a">

这个证书地址配置对了吗？ 如果是docker部署的要docker内的地址

**Comment by tangtaoit** [comment]
你也可以将wss证书配置到nginx上 然后 nginx的wss转WuKongIM的ws。
