### ISSUE TITLE
关于小程序的类似待办提醒功能

### ISSUE THREAD

**Issue by xsbl-001** [WuKongIM/WuKongIM#20]
服务端往im发送消息，客户端该怎样去监听拿到这个消息，我试着监听了，但是没反应，小程序用uniapp写的

**Comment by tangtaoit** [comment]
1. 你客户端需要先用一个uid和token去调用sdk的connect方法建立与WuKongIM的长连接。
2. 监听消息 (记得页面销毁的时候移除简单)
```
// 消息监听
WKSDK.shared().chatManager.addMessageListener((message: Message) => {
 console.log(message)
});
```
3. 服务端发送消息的时候 指定channel_id为连接的uid，channel_type为1 （1表示个人频道）（接口说明：https://githubim.com/api/message.html#%E5%8F%91%E9%80%81%E6%B6%88%E6%81%AF）
