### ISSUE TITLE
为什么我这两个设备都在线 发送消息 webhook还走离线通知啊 msg.offline

### ISSUE THREAD

**Issue by donal520** [WuKongIM/WuKongIM#200]
![微信图片_20241120191738](https://github.com/user-attachments/assets/44c3bb6b-68f4-4cfa-9fa4-26f322770128)

**Comment by tangtaoit** [comment]
WuKongIM有用户和设备的概念，设备也分主设备和从设备，拿微信来说，手机微信算主设备，Web微信算从设备。

同一个账号如果手机微信不在线，Web微信在线， 收到消息后，手机微信也能收到离线通知。

结论： 主设备不在线就会收到离线通知事件

**Comment by donal520** [comment]
能否加个字段,告诉的主从设备标识的离线消息,下次同步啊

**Comment by tangtaoit** [comment]
要这个干啥？ 你只要根据to_uids里的uid去推离线消息即可

**Comment by donal520** [comment]
问题是我APP在线啊,网页版没在线.我想收到后 知道是网页版的离线消息,下次网页版登录了就给他同步过去啊

**Comment by donal520** [comment]
我看到了.主有主设备没在线才会收到消息

**Comment by tangtaoit** [comment]
> 问题是我APP在线啊,网页版没在线.我想收到后 知道是网页版的离线消息,下次网页版登录了就给他同步过去啊

是离线通知 不是离线消息，离线消息这个同步最近会话就可以

**Comment by donal520** [comment]
收到
