### ISSUE TITLE
宝塔Docker部署后没有启动命令

### ISSUE THREAD

**Issue by cnanzhi** [WuKongIM/WuKongIM#204]
宝塔Docker部署后没有启动命令，编辑容器会导致容器丢失。

**Comment by tangtaoit** [comment]
宝塔不是很熟，按照官网推荐的教程部署 https://githubim.com/install/docker-compose/singlenode.html

**Comment by cnanzhi** [comment]
启动命令是啥，/bin/sh -c /home/app  每次启动，配置会被初始化
