### ISSUE TITLE
如何发送图片和语音消息？

### ISSUE THREAD

**Issue by liyaqi1217** [WuKongIM/WuKongIM#208]
发送图片和语音消息 ，文档上说自己上传图片，是通过我们自己后台的上传接口，把图片上传到我们的服务器，然后返回图片地址就行吗？那下边这个 sdk去上传文件，需要实现上传文件的数据源，这个数据源又是做什么用的，是需要修改IM的配置吗？
![微信截图_20241125170732](https://github.com/user-attachments/assets/6ecf3abc-4f84-48c0-9476-79b8bdd67808)

**Comment by tangtaoit** [comment]
WuKongIM并不存储图片或语音，实现发送图片或语音的流程应该是：消息显示在UI上状态为发送中 —> 将图片上传到自己的文件服务器 —> 获取到下载地址 —→ 将下载地址发送给对方 —> UI上消息显示发送成功。

针对上述流程，开发者只需要实现图片上传到自己服务器和将下载地址设置到消息内的逻辑。

以JSSDK举例：

1. 开发者需要自定义附件消息，参考文档 [[https://githubim.com/sdk/jssdk/advance.html#自定义附件消息](https://githubim.com/sdk/jssdk/advance.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%99%84%E4%BB%B6%E6%B6%88%E6%81%AF)](https://githubim.com/sdk/jssdk/advance.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%99%84%E4%BB%B6%E6%B6%88%E6%81%AF)
2. 实现文件上传到文件服务器的逻辑，参考文档 [[https://githubim.com/sdk/jssdk/datasource.html#文件上传数据源](https://githubim.com/sdk/jssdk/datasource.html#%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0%E6%95%B0%E6%8D%AE%E6%BA%90)](https://githubim.com/sdk/jssdk/datasource.html#%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0%E6%95%B0%E6%8D%AE%E6%BA%90)
