### ISSUE TITLE
配置了wk配置文件，但是wss依然报错

### ISSUE THREAD

**Issue by wenchao19** [WuKongIM/WuKongIM#209]
配置了wk配置文件，但是wss依然报错 index-f8292fd8.js:24 Mixed Content: The page at 'https://xx.com/chatdemo/?uid=8003#/chat?uid=8003&token=' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://xxx:5200/'. This request has been blocked; this endpoint must be available over WSS.
配置文件如下  
mode: "release" # 运行模式 模式 debug 测试 release 正式 bench 压力测试
#addr: "tcp://0.0.0.0:5100" # tcp监听地址
#httpAddr: "0.0.0.0:5001" #  http api的监听地址  默认：0.0.0.0:5001
rootDir: "./wukongimdata" # 数据存储目录
#tokenAuthOn: false # 是否开启token验证 默认为false，如果不开启任何人都可以连接到此节点，生产环境建议开启
#managerUID: "" # 管理员UID  默认为 ____manager
#managerToken: "" # 管理员token 如果此字段有值，则API接口需要在请求头中添加token字段，值为此字段的值
#wsAddr: "ws://0.0.0.0:5200"  # websocket ws 监听地址 
wssAddr: "wss://0.0.0.0:5210"  # websocket wss 监听地址 如果打开则需要进行 wssConfig相关的证书配置
#whitelistOffOfPerson: true # 是否关闭个人白名单 默认为true表示关闭个人白名单的验证
external: # 公网配置
 ip: "" # 节点外网IP，客户端能够访问到的IP地址，如果客户端是内网使用，这里也可以填写内网IP
#  tcpAddr: "" #  默认自动获取， 节点的TCP地址 对外公开，APP端长连接通讯  格式： ip:port  
#  wsAddr: "" # 默认自动获取， 节点的wsAdd地址 对外公开 WEB端长连接通讯 格式： ws://ip:port  （支持域名配置）
 wssAddr: "wss://0.0.0.0:5210" # 对外的wssAddr地址，也就是客户端真正连接的地址 格式：wss://ip:port （支持域名配置）
#  monitorAddr: "" # 默认自动获取， 节点的monitor地址 对外公开 监控服务 格式： ip:port
#  apiUrl: "" # 默认自动获取， 节点的http地址 对外公开 http api 格式： http://ip:port
wssConfig:
 certFile: "/www/server/panel/vhost/cert/xx.pem" # wss证书文件路径
 keyFile: "/www/server/panel/vhost/cert/xx.pem" # wss证书key文件路径

**Comment by tangtaoit** [comment]
配置的external.wssAddr是对外的wssAddr也就是web连接的地址，要配你这个证书对应的域名
