### ISSUE TITLE
如何带入业务中的用户姓名或者昵称

### ISSUE THREAD

**Issue by csharpniubi** [WuKongIM/WuKongIM#21]
目前吧业务中的用户ID 传入悟空IM中,
但是这样在客服页面里只有ID,
不容易区分谁是谁,
所以想再客服页面展示用户姓名或者其他更多信息
请问如何封装修改

**Comment by tangtaoit** [comment]
姓名和其他更多信息都属于业务服务器，你的业务服务应该提供一个获取设置信息的接口，比如用户信息接口（唐僧叨叨统一称为频道信息接口）。

以收到消息展示发送者的昵称和其他信息为例：

1. 收到消息的时候，消息只有fromUID，我们可以通过fromUID去缓存取用户信息。
2. 如果没有换成信息，我们可以异步通过这个fromUID调用你业务端的用户信息接口获取到用户信息并放入缓存。
3. 然后重新触发render。

其实这个逻辑jssdk已经实现了，你只需要 `WKSDK.shared().config.provider.channelInfoCallback` 方法

参考唐僧叨叨web的实现 https://github.com/TangSengDaoDao/TangSengDaoDaoWeb/blob/main/packages/tsdaodaodatasource/src/module.ts#L34C45-L34C45

然后用户如下几个方法：

伪代码如下：
```ts

mounted:

// 监听频道信息的变化
WKSDK.shared().channelManager.addListener((channelInfo: ChannelInfo) => {
            this.setState({}) // 重新触发render这样会重新调用getChannelInfo 这时候getChannelInfo方法就有值了
})

render：

// 从缓存获取频道信息
 const fromChannelInfo = WKSDK.shared().channelManager.getChannelInfo(fromChannel)
if(!fromChannelInfo) { // 不存在则远程fetch
   WKSDK.shared().channelManager.fetchChannelInfo(fromChannel) // 如果获取成功会触发addListener
}


```

总而言之可以参考唐僧叨叨的Web版，只悟空IM一个产品级的Demo案例

**Comment by fulus06** [comment]
可以把头像、昵称、业务ID包装到消息体里

**Comment by tangtaoit** [comment]
> 可以把头像、昵称、业务ID包装到消息体里

每条消息都带，浪费流量
