### ISSUE TITLE
已连接wss,但是前端显示断开，传输消息为N/A

### ISSUE THREAD

**Issue by wenchao19** [WuKongIM/WuKongIM#214]
服务器输出 /11/26 - 10:51:50 | 404 |      39.882µs |       127.0.0.1 | GET      "/"    
已连接wss，但是显示断开，浏览器data传输消息为N/A

**Comment by tangtaoit** [comment]
wss地址如果域名直接解析到你服务器的 没有做类似nginx之类的，external.wssAddr的地址应该是 wss://域名:5210

**Comment by wenchao19** [comment]
做了nginx ,配置如下：
    location / {
        proxy_pass http://127.0.0.1:5001; # 代理到后端服务
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
    }
    
    location /wss {  # 根据你的需求调整路径
        proxy_pass http://127.0.0.1:5210;  # 指向你的后端服务器地址和端口号
        proxy_set_header Upgrade $http_upgrade;  # 传递升级头信息给后端服务器
        proxy_set_header Connection 'upgrade';  # 传递连接头信息给后端服务器
        proxy_http_version 1.1;  # 使用1.1版本的HTTP协议，确保与后端服务器兼容
        proxy_set_header Host $host;  # 传递主机头信息给后端服务器
        proxy_buffering off;  # 关闭代理缓冲，以确保实时通信不被中断
    }

**Comment by tangtaoit** [comment]
> 做了nginx ,配置如下： location / { proxy_pass http://127.0.0.1:5001; # 代理到后端服务 proxy_http_version 1.1; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection "upgrade"; proxy_read_timeout 86400; }
> 
> ```
> location /wss {  # 根据你的需求调整路径
>     proxy_pass http://127.0.0.1:5210;  # 指向你的后端服务器地址和端口号
>     proxy_set_header Upgrade $http_upgrade;  # 传递升级头信息给后端服务器
>     proxy_set_header Connection 'upgrade';  # 传递连接头信息给后端服务器
>     proxy_http_version 1.1;  # 使用1.1版本的HTTP协议，确保与后端服务器兼容
>     proxy_set_header Host $host;  # 传递主机头信息给后端服务器
>     proxy_buffering off;  # 关闭代理缓冲，以确保实时通信不被中断
> }
> ```

你在nginx上配置了wss 就不需要在wukongim配置了，你proxy_pass转发到ws地址即可也就是http://127.0.0.1:5200
然后extenral.wssAddr指定前端要连的地址，也就是你nginx的wss地址
