### ISSUE TITLE
WuKongIM支持语音通话吗

### ISSUE THREAD

**Issue by yangjinfeng** [WuKongIM/WuKongIM#215]
WuKongIM支持语音通话吗？像微信语音那样的余音实时交互，我们在尝试用netty做后台的语音通话服务转发，有延时没处理好

**Comment by tangtaoit** [comment]
语音通话一般用webrtc，WuKongIM可以用于发起呼叫和挂断指令的信令，但是数据一般还是走webrtc的协议

**Comment by Mor1arty** [comment]
希望像discord那样支持随进随退的群组语音
