### ISSUE TITLE
关于集群部署，数据存储，SDK的相关问题

### ISSUE THREAD

**Issue by Cloud-Yao** [WuKongIM/WuKongIM#22]
1. 我想知道悟空IM可以支持集群部署吗？如何保证服务的高可用？
2. 悟空IM的文档关于消息存储的相关事项，只是简单提了一下“自研消息DB”，没有提到具体的细节，不知道能否对这部分内容在官方文档中做出详细的补充说明？
3. 想问一下有没有具体的性能测试报告，部署调优相关方面的文档，包括如何支持业务的业务用户的持续增长？
4. 打听一下flutter的相关SDK大概什么时间能出炉？

**Comment by tangtaoit** [comment]
> 1. 我想知道悟空IM可以支持集群部署吗？如何保证服务的高可用？

 目前不支持，集群在开发中

> 2. 悟空IM的文档关于消息存储的相关事项，只是简单提了一下“自研消息DB”，没有提到具体的细节，不知道能否对这部分内容在
官方文档中做出详细的补充说明？

1. 如果是使用层面的话，不需要关系这个DB，就像使用kafka一样不需要关系kafka的消息db如何实现的。
2. 悟空IM有提供消息相关的接口，比如历史消息查询。
3. 如果需要多维度查询消息，可以通过监听webhook将消息存储在自己的业务服务器上，比如可以使用MYSQL存储也可以使用ES存储等，参考Webhook相关文档，也可以参考唐僧叨叨案例

> 3. 想问一下有没有具体的性能测试报告，部署调优相关方面的文档，包括如何支持业务的业务用户的持续增长？

IM服务器最重要的一个性能指标就是消息QPS，目前我们测试下来 16w+/s，你也可以自己测试。测试文档： https://githubim.com/guide/stress.html

> 打听一下flutter的相关SDK大概什么时间能出炉？

flutter已经在开发中，大概2周 ～ 1月内。

**Comment by zhanyuezhong** [comment]
看到0依赖，感觉和牛叉，想看看如何在0依赖情况下作集群支持，最后发现只有单机

**Comment by superlbr** [comment]
翻了下代码，DB是[bblot](https://github.com/etcd-io/bbolt)

**Comment by superlbr** [comment]
集群是否已经可用？

**Comment by tangtaoit** [comment]
> 翻了下代码，DB是[bblot](https://github.com/etcd-io/bbolt)

bbolt db是用来存元数据的，没有存消息

**Comment by tangtaoit** [comment]
> 集群是否已经可用？

开发中

**Comment by snamper** [comment]
集群2023年年底完成

**Comment by tangtaoit** [comment]
> 集群2023年年底完成

哥 你是无限的给我压力啊 😄

**Comment by superlbr** [comment]
请问数据是否可以直接迁移到集群

**Comment by tangtaoit** [comment]
> 请问数据是否可以直接迁移到集群

那是不可能的，后面会开发个自动迁移工具
