### ISSUE TITLE
关于主从设备的概念模糊的问题

### ISSUE THREAD

**Issue by Cloud-Yao** [WuKongIM/WuKongIM#226]
<img width="575" alt="image" src="https://github.com/user-attachments/assets/488743cd-979e-4260-96e1-4f2875423ea5">
这是我在Issue中找的一张说明图，感觉不是太清楚。  图片提到 “相同用户 + 相同设备标识 + 主设备” 会互相挤下线，如果我的计划像微信那样，手机端App只能同时登录在一台手机上（不管什么手机系统，只能同时在线一台手机），PC的应用同样只能登录在一台电脑上，手机App和电脑应用互不影响，那么这个device_flag 和 device_level该怎么设计呢？  

我猜测的设计：把手机App和PC端设计为两个不同的device_flag,  （假如是0 和 1）， 然后它们都是主设备，这样这手机App和电脑就不会影响，其他的手机如果登录上来，因为相同主设备会将之前那个挤下线（手机端登录会把之前登录的那个手机挤下去，PC端登录会把之前的那个PC挤下去），所有就满足需求，可以这么理解吗？

总结一下就是    
    手机端  device_flag = 0, device_level = 1 (主设备)
    PC端    device_flag = 1, device_level = 1 (主设备)

另外一个问题是，我看图中有提到 “设置 device_flag = 4 表示 安卓， device_flag = 5 表示 IOS”， 这也就是说，device_flag 并不是只有 0 或者 1 这两个值，可以自己自定义，是吗？

**Comment by functionName** [comment]
另外一个问题是，我看图中有提到 “设置 device_flag = 4 表示 安卓， device_flag = 5 表示 IOS”， 这也就是说，device_flag 并不是只有 0 或者 1 这两个值，可以自己自定义，是吗？

**Comment by functionName** [comment]
手机端 device_flag = 0, device_level = 1 (主设备)
PC端 device_flag = 1, device_level = 1 (主设备)    这个应该可以

**Comment by tangtaoit** [comment]
你的理解是对的，device_flag可以自定义

**Comment by Cloud-Yao** [comment]
OK 感谢
