### ISSUE TITLE
修改wk.yaml的conversation.cacheExpire 貌似数据库被重置了

### ISSUE THREAD

**Issue by cnyunguo** [WuKongIM/WuKongIM#227]
大佬们，悟空IM部分问题，
修改wk.yaml的conversation.cacheExpire，
docker重启后，/conversation/sync 接口，获取用户活跃的最近会话 s.s.store.GetLastConversations 返回的 len(conversations) 是 0，
貌似数据库被重置了，请问有什么办法规避，或正确的升级更新是什么样的。

**Comment by tangtaoit** [comment]
升级到最新v2版本
