### ISSUE TITLE
wukongim的数据库怎么看呀？

### ISSUE THREAD

**Issue by momochong0** [WuKongIM/WuKongIM#23]
data下面有个wukongim.db，sqlite连接提示：file is not a database

**Comment by tangtaoit** [comment]
wukongim.db是使用的boltdb（一个key value数据库）WuKongIM主要用来存储一些元数据，比如频道基础数据  链接地址 https://github.com/etcd-io/bbolt

目前我没看到boltdb有查看工具。

消息数据是采用LSM自研的存储方式，目前提供monitor后台有提供简单查询

**下面说明比较重要‼️**

如果纠结这个查询，可能没完全理解WuKongIM的使用方式。

**对于元数据：**
app端是先调用你的业务服务器，你的业务服务器再调用WukongIM，所以你业务服务器应该有比WukongIM更全的数据，所以为什么要去WukongIM查？WukongIM主要保存的是一些channelID，和uid之类的数据，查询也无意义。

**对于消息数据：**
消息数据WukongIM有webhook机制，会将所有消息有机的推送给你的业务服务器，你业务服务器可以使用MYSQL存储，也可以使用ES存储或者其他任意方式存储，所以如果分析消息数据的需求，应该也不需要去WukongIM里查询。

**WukongIM提供的消息查询**

WukongIM提供的消息查询主要是用做消息漫游，离线消息之类的简单索引，如果是复杂索引，应该在业务层查询
