### ISSUE TITLE
发送者权限判断失败的情况下没处理，导致出现无限循环

### ISSUE THREAD

**Issue by skyasker** [WuKongIM/WuKongIM#234]
// 发送者权限判断
func (c *Channel) processPermission(channelId string, channelType uint8, msgs []*reactor.ChannelMessage) {

	// 记录消息轨迹
	for _, m := range msgs {
		m.Track.Record(track.PositionChannelPermission)
	}

	reasonCode, err := c.hasPermissionForChannel(channelId, channelType)
	if err != nil {
		c.Error("hasPermissionForChannel error", zap.Error(err))
		reasonCode = wkproto.ReasonSystemError
	}
	if reasonCode != wkproto.ReasonSuccess {
		c.Info("hasPermissionForChannel failed", zap.String("channelId", channelId), zap.Uint8("channelType", channelType), zap.String("reasonCode", reasonCode.String()))
	}

**Comment by tangtaoit** [comment]
已修复
