### ISSUE TITLE
存储消息完成再发sendAck，客户端看起来延迟高

### ISSUE THREAD

**Issue by skyasker** [WuKongIM/WuKongIM#244]

**Comment by tangtaoit** [comment]
不是存储的原因，这个延迟高现在在优化

**Comment by skyasker** [comment]
嗯，注意到如果鉴权失败，回执会快很多

**Comment by SomenLenk** [comment]
我们也遇到类似的问题，有有什么优化思路吗

**Comment by tangtaoit** [comment]
已修复

**Comment by skyasker** [comment]
使用了新提交的代码，这个问题任然存在。原因是存储成功后才发送确认sendAck，存储过程比较耗时。但是如果不存储就得不到messageSeq。把messageSeq交给数据库生成，消息就必须先存储再投递。感觉这种设计有很多限制，比如确认延迟，消息无法先缓冲再异步入库等

**Comment by tangtaoit** [comment]
> 使用了新提交的代码，这个问题任然存在。原因是存储成功后才发送确认sendAck，存储过程比较耗时。但是如果不存储就得不到messageSeq。把messageSeq交给数据库生成，消息就必须先存储再投递。感觉这种设计有很多限制，比如确认延迟，消息无法先缓冲再异步入库等

先存储再sendack是为了消息100%不丢，如果是先会sendack，如果消息存储失败了呢？那这消息在用户看来就是丢了 因为用户显示发送成功了，要想消息不丢必先存储 这个是逃不掉的

**Comment by tangtaoit** [comment]
目前消息在150-500ms之间吧，现在的机制是你发的越多速度越快，因为消息是批量处理的，所以这个延迟应该是可以接受的

**Comment by skyasker** [comment]
先缓冲再持久化这个过程也可以设计一些机制保证消息不丢。问题在于序列号由数据库生成，由于数据库很慢，提高了消息投递的时延。对于IM系统来说存储延迟高点还好，因为最终总能拉到，但是投递延迟的影响就大了。150-500ms其实对于一些实时性更高的场景是不可接受的（比如CMD的场景）。问题的关键是要把序列号生成和数据存储分开，不要让存储过程影响消息投递

**Comment by tangtaoit** [comment]
> 先缓冲再持久化这个过程也可以设计一些机制保证消息不丢。问题在于序列号由数据库生成，由于数据库很慢，提高了消息投递的时延。对于IM系统来说存储延迟高点还好，因为最终总能拉到，但是投递延迟的影响就大了。150-500ms其实对于一些实时性更高的场景是不可接受的（比如CMD的场景）。问题的关键是要把序列号生成和数据存储分开，不要让存储过程影响消息投递

有什么机制能保证在缓存下没有持久化的时候重启了 消息不丢？

**Comment by skyasker** [comment]
缓冲的目的是为了异步批量写入，不是一定是内存缓存。咱们之前单机版也是先持久化，但延迟就低的多，只是目前分布式存储延迟变得高了，再存储后分配seq就会把延迟啦得很高

**Comment by tangtaoit** [comment]
1. 持久化的缓存还是持久化
2. 目前WukongIM批量写入，你发一条延迟150-500ms左右，你同时发1万条也是这个延迟，并不是你认为的排队一条一条的存储。
3. 如果你应用程序对延迟要求高，可以调整 pkg/cluster/reactor/options.go下的TickInterval参数，默认是150ms，你可以调到50ms，这样消息发送延迟可以到50ms-150ms之间。

**Comment by skyasker** [comment]
并不能改变投递时延被存储时延限制
