### ISSUE TITLE
关于app启动后获取聊天列表的问题

### ISSUE THREAD

**Issue by bycw** [WuKongIM/WuKongIM#33]
1、例如当前用户之前和5个人聊天，那么app启动后如何获取到这5个聊天列表呢？
2、“同步离线的最近会话”这个接口，是指当前用户离线其间，其它用户发向当前用户发的消息吗？
3、“同步离线的命令消息”这个接口，作用是什么呢？

**Comment by tangtaoit** [comment]
1. 可以通过 [同步最近会话列表接口获取](https://githubim.com/api/conversation.html#%E5%90%8C%E6%AD%A5%E6%9C%80%E8%BF%91%E4%BC%9A%E8%AF%9D) (注意需要开启最近会话的配置)，sdk内会维护conversation，监听conversation的变化然后渲染UI即可
2. 是的
3. 这个主要用于同步一些指令的消息，这些消息不显示在UI上，只是app内部执行。

**Comment by bycw** [comment]
> 1. 可以通过 [同步最近会话列表接口获取](https://githubim.com/api/conversation.html#%E5%90%8C%E6%AD%A5%E6%9C%80%E8%BF%91%E4%BC%9A%E8%AF%9D) (注意需要开启最近会话的配置)，sdk内会维护conversation，监听conversation的变化然后渲染UI即可

每次app启动都要同步最近会话列，是不是app本地不会保存历史记录？

**Comment by bycw** [comment]
> 1. 可以通过 [同步最近会话列表接口获取](https://githubim.com/api/conversation.html#%E5%90%8C%E6%AD%A5%E6%9C%80%E8%BF%91%E4%BC%9A%E8%AF%9D) (注意需要开启最近会话的配置)，sdk内会维护conversation，监听conversation的变化然后渲染UI即可


是不是说，app调用同步最近会话列表接口，悟空Im通过sdk给app推送最近会话数据，而不是通过api接口反回数据给app？

**Comment by tangtaoit** [comment]
是通过API调用的，其实这些你不需要关心，sdk都做好了 你只需要实现对应的最近会话列表的数据源即可 以JSSDK为例：参考 https://githubim.com/sdk/javascript.html#%E6%95%B0%E6%8D%AE%E6%BA%90%E8%AE%BE%E7%BD%AE 的 WKSDK.shared().config.provider.syncConversationsCallback 然后相关的最近会话的sdk的方法 都在WKSDK.shared().conversationManager这个里 可以看看

**Comment by kangsange** [comment]
数据源这块还是看不明白，能写个demo吗或者录个教程啥的?
