### ISSUE TITLE
关于sdk是否保存消息到本地？

### ISSUE THREAD

**Issue by bycw** [WuKongIM/WuKongIM#34]
app端发送或接收后的数据，sdk是否会将这些消息保存到app本地？如果保存，需要sdk的哪个方法去读取呢？

**Comment by tangtaoit** [comment]
除了web，其他sdk都有保存，我不知道你问的是那个语言的,比如 iOS的在 关于消息操作的都在WKSDK.shared.chatManager 这个管理者里，其他的也类似。如果不会使用还可以参考唐僧叨叨的项目 https://github.com/TangSengDaoDao/TangSengDaoDaoServer  唐僧叨叨就是用悟空IM的sdk开发的
