### ISSUE TITLE
docker 部署失败

### ISSUE THREAD

**Issue by honpchen** [WuKongIM/WuKongIM#4]
docker: Error response from daemon: create ./wukongim: "./wukongim" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.

**Comment by tangtaoit** [comment]
Thank you for your feedback, use the following command:

`docker run -d -p 5000:5000 -p 5100:5100 -p 5200:5200 -p 5300:5300  --name wukongim -v ~/wukongim:/root/wukongim  wukongim/wukongim:latest`
