### ISSUE TITLE
uniapp编译的小程序报错, 是不支持吗

### ISSUE THREAD

**Issue by tangtaoit** [WuKongIM/WuKongIM#45]
![131551697528369_ pic](https://github.com/WuKongIM/WuKongIM/assets/3895878/ce39aa49-5810-4524-8959-d5ad8d08883d)

**Comment by tangtaoit** [comment]
jssdk 更新到1.2.2试试

**Comment by Dorahui** [comment]
uniapp编译后的小程序, 可以连接, 但是无法使用Websocket的send和close方法
![image](https://github.com/WuKongIM/WuKongIM/assets/106006942/3209f792-efe5-423c-a072-34d46d2813bb)
