### ISSUE TITLE
windows环境运行一段时间后报错

### ISSUE THREAD

**Issue by zhangxilong123** [WuKongIM/WuKongIM#46]
![7736606edf3b3ac98ebd159bd542110](https://github.com/WuKongIM/WuKongIM/assets/52381336/bc277edc-de13-47f1-b68e-b3027ff2edf8)

**Comment by tangtaoit** [comment]
windows环境下网络层可能有BUG 目前windows环境只支持开发，正式发布 建议使用linux环境，linux的网络层实现跟windows的不一样。
