### ISSUE TITLE
uniapp编译后的小程序报错

### ISSUE THREAD

**Issue by Dorahui** [WuKongIM/WuKongIM#47]
![image](https://github.com/WuKongIM/WuKongIM/assets/106006942/c5dcb97f-511c-421f-b13e-d474381f0dbb)
![image](https://github.com/WuKongIM/WuKongIM/assets/106006942/72e1f2ab-0d4b-409a-a906-ab2cb607adcd)
![image](https://github.com/WuKongIM/WuKongIM/assets/106006942/23c858bb-8d02-416e-8c00-d6a3bb5a980e)
可以连接, 但是无法使用Websocket的send和close方法

**Comment by tangtaoit** [comment]
如果web和其他环境没问题，只有微信小程序出现这情况，一般是连接的地址不是wss:// 引起的，微信小程序需要wss协议才可以通讯
