### ISSUE TITLE
安装和运行的2个问题

### ISSUE THREAD

**Issue by lhc-ltd** [WuKongIM/WuKongIM#5]
问题1：安装脚本识别系统架构问题
在x86_64系统下安装脚本报错：Unsupported architecture: x86_64
这个问题手动将ARCH参数改了可以安装成功
![err1](https://github.com/WuKongIM/WuKongIM/assets/57882830/a2a045d0-542d-4b50-8890-1d6237c91a08)

问题2：运行时报错，见图
![err2](https://github.com/WuKongIM/WuKongIM/assets/57882830/95f68c90-2394-44cb-b2f1-48fce2b74aa7)

网上查了下，是rename命令不能跨盘的问题，建议修改为mv命令

烦请核实下是否存在以上问题，谢谢

**Comment by tangtaoit** [comment]
感谢🙏，现在已经修复，看最新文档
