### ISSUE TITLE
安装好以后演示走不通

### ISSUE THREAD

**Issue by a537303** [WuKongIM/WuKongIM#50]
![IMG_1336](https://github.com/WuKongIM/WuKongIM/assets/148688959/5846ca13-3267-4691-b2db-91ec0acbb6a2)
演示返回的是这个地址，而不是服务器地址，修改配置以后仍然返回的是这个

**Comment by tangtaoit** [comment]
按照这个教程来安装：https://tsdaodao.com/dev/backend/deploy-compose.html

这个地址返回的是在.env配置的 EXTERNAL_IP参数（注意文件名是.env）

**Comment by a537303** [comment]
我是安装这个来安装的
![IMG_1344](https://github.com/WuKongIM/WuKongIM/assets/148688959/b6ab7ac9-b2c4-49b9-b6c4-a9c061be6188)
安装好以后的文件
![IMG_1343](https://github.com/WuKongIM/WuKongIM/assets/148688959/67af65db-2ac3-4a33-ad2c-bacaf7105a44)

然后修改了配置文件wukongim/wk.yaml的external:
  ip: 'xxx.xxx.xxx.xxx'
填写了ip为我的服务器ip地址，重启之后，跑演示返回的就一直是内网ip了。

**Comment by tangtaoit** [comment]
哦哦，上面说错了，上面说的是唐僧叨叨的安装方式 串频道了😂

你这个问题，应该是yaml格式改乱了，你可以试试改下mode的配置看有没有生效，如果没生效那就是你改什么都不会生效，那应该就是yaml格式改坏了，yaml要求严格缩进，检查下。

**Comment by a537303** [comment]
受折磨好几天，总算搞定了，可以跑了，感谢感谢！
