### ISSUE TITLE
File is too small,sanity check mode is full

### ISSUE THREAD

**Issue by superlbr** [WuKongIM/WuKongIM#51]
POST /conversation/sync 报错

**Comment by tangtaoit** [comment]
File is too small,sanity check mode is full是DEBUG日志 不是错误日志，要看具体错误日志才能判断

**Comment by superlbr** [comment]
嗯嗯，一开始调试取不到数据，方了

**Comment by WakeOneT** [comment]
怎么解决的，我也是这样，然后报错跟着
"msg":"【Client[94]】移除重试队列里的消息失败！","error":"ID not in flight","messageSeq":0,"uid":"d3e7c51541f44316942fc5325b1ca735","clientID":94,"deviceFlag":1,"deviceID":"92d628d02936de25779b6ae462031390W","messageID":1727367504646381568} ，请教如何处理的

**Comment by tangtaoit** [comment]
> 怎么解决的，我也是这样，然后报错跟着 "msg":"【Client[94]】移除重试队列里的消息失败！","error":"ID not in flight","messageSeq":0,"uid":"d3e7c51541f44316942fc5325b1ca735","clientID":94,"deviceFlag":1,"deviceID":"92d628d02936de25779b6ae462031390W","messageID":1727367504646381568} ，请教如何处理的

这个不用处理，到时候把这日志调成debug
