### ISSUE TITLE
如何判定大群&为什么要区分大群

### ISSUE THREAD

**Issue by Administration-LGL** [WuKongIM/WuKongIM#54]
悟空IM源码中，很多地方都会区分是否大群，想了解一下
1.多大算大群，这个标准是用户定义的吗(源码中暂时没发现大群判定标准)
2.为什么要区分大群(阅读网上的文章，大概是投递消息占用太多资源，但我的理解不管你是否是大群，你都要投递，所以做出区分还有其他方面的考虑吗)

**Comment by tangtaoit** [comment]
1. 悟空IM的大群意味着没有上线。只要硬件够用。（分布式支持后大群会分压到各个节点）
2. 大群跟普通群唯一的区别是，服务端不维护每个用户大群的最近会话（客户端维护）。这也是大群最耗性能的地方，比如1万人的大群。一条消息，就要变动每个用户的此群的最近会话，也就是要修改一万个用户的会话。那是相当消耗性能的，至于消息投递的话 不是瓶颈所在，毕竟1万人群，不可能都在线，（分布式后，投递也会分压力各个节点投递）
