### ISSUE TITLE
 "/conversation/sync" api error 

### ISSUE THREAD

**Issue by WakeOneT** [WuKongIM/WuKongIM#65]
"msg":"【Client[94]】移除重试队列里的消息失败！","error":"ID not in flight","messageSeq":0,"uid":"d3e7c51541f44316942fc5325b1ca735","clientID":94,"deviceFlag":1,"deviceID":"92d628d02936de25779b6ae462031390W","messageID":1727367504646381568}

请问如何修复这个报错，或者手动找到消息移除？

**Comment by tangtaoit** [comment]
这个不用处理，是重试或多设备登录引起的多次ack，其实已经移除了，所以再次移除就会报错，可以忽略这个错误
