### ISSUE TITLE
wss 无法连接

### ISSUE THREAD

**Issue by vera-byte** [WuKongIM/WuKongIM#66]
<img width="1025" alt="image" src="https://github.com/WuKongIM/WuKongIM/assets/42960387/ed847dfd-a959-48a4-9980-d65ae60063a8">
<img width="389" alt="image" src="https://github.com/WuKongIM/WuKongIM/assets/42960387/e33574af-242f-457c-aa42-a8695fd03e08">
<img width="535" alt="image" src="https://github.com/WuKongIM/WuKongIM/assets/42960387/9fe97d9a-42d2-48cc-b54c-7b44a078bcdb">

**Comment by vera-byte** [comment]
<img width="1058" alt="image" src="https://github.com/WuKongIM/WuKongIM/assets/42960387/3b3ef17c-658f-4add-8201-407f85fe38e8">

**Comment by tangtaoit** [comment]
external下的wssAddr的IP改成你证书对应的域名
