### ISSUE TITLE
socket只在线三秒

### ISSUE THREAD

**Issue by kangsange** [WuKongIM/WuKongIM#67]
用执行文件部署，按照文档配置，开放了5100 5200 5300 5001 ，也通过接口注册了用户，成功返回200，但socket连上就断
![image](https://github.com/WuKongIM/WuKongIM/assets/37733022/3c454680-fd3e-43d6-b5cb-036c14e4a618)
请问这是咋回事呢

**Comment by tangtaoit** [comment]
你这是用什么工具连接的？ 使用sdk去连接   需要发送连接认证包 通过认证后 服务器才维持长连接

**Comment by kangsange** [comment]
搞明白了，我是在APICloud里面用jssdk去连接的，但是在里面不能连接成功，=

**Comment by kangsange** [comment]
能不能出一个apicloud的sdk呢？只需要对现有的sdk进行一下封装就好了，但是需要原生开发的能力

**Comment by tangtaoit** [comment]
> 能不能出一个apicloud的sdk呢？只需要对现有的sdk进行一下封装就好了，但是需要原生开发的能力

https://www.apicloud.com/portal-web/close  apicloud都停止运营了

**Comment by kangsange** [comment]
apicloud被用友收购了，原官网所以停止运营了，现在搬迁到用友官网了：https://developer.yonyou.com/docs/，但我们老用户还是习惯称为apicloud，apicloud可以把原生的android和ios模块按照他们平台的要求进行封装后使用，通过js可以调用原生的模块，封装的文档在上面网址的左下角：
![image](https://github.com/WuKongIM/WuKongIM/assets/37733022/699f0569-3ae6-4309-b000-b9ee87906fa7)
，您看一下文档，如果可以的话，封装一下，万分感谢
