### ISSUE TITLE
配置tokenAuthOn的使用

### ISSUE THREAD

**Issue by Brother-Dragon** [WuKongIM/WuKongIM#68]

**Comment by tangtaoit** [comment]
你们服务端需要调用/user/token的接口告诉WuKongIM用户的token http://githubim.com/api/user.html

从日志看服务器没有给WuKongIM token或给的是空

**Comment by Brother-Dragon** [comment]
> 你们服务端需要调用/user/token的接口告诉WuKongIM用户的token http://githubim.com/api/user.html
这个/user/token接口传递的token和返回的token都是在配置文件中的managerToken吗

**Comment by Brother-Dragon** [comment]
这个/user/token 接口传参的token就是配置文件中的managerToken吗，然后把这个token传递给回前端吗，前端再去调用WKSDK.shared().config.token进行传参么

**Comment by tangtaoit** [comment]
/user/token 接口传参的token是你自己定义的 只要保证接口传递的token跟 前端sdk连接的token一致即可
