### ISSUE TITLE
集群部署PC端可以正常demo演示，flutter移动端TCP不通，请问yaml文件怎么配置

### ISSUE THREAD

**Issue by xxd296008** [WuKongIM/WuKongIM#69]
yaml文件这样配置，ws pc端可以正常聊天，移动端ip写的36.139.34.280:30005，一致提示连接中，
客户端日志如下：
I/flutter (20717): debug:socketonDone
I/flutter (20717): error:发送消息失败false
I/flutter (20717): info:连接地址--->36.139.34.280:30005
I/flutter (20717): 连接中

yaml配置如下：
mode: "debug"
external: 
ip: "36.139.34.280"
tcpAddr: "36.139.34.280:30005"
wsAddr: "ws://36.139.34.280:32660"

**Comment by tangtaoit** [comment]
30005是对应原来的5100端口吗 是不是做了nginx转发 转发是转发tcp 而不是http或ws

**Comment by xxd296008** [comment]
![e8](https://github.com/WuKongIM/WuKongIM/assets/118756868/a5e33bdd-783f-4139-8e26-c401719c751f)
30005对应的5100端口  用的集群K8S部署的，绑定的公网IP映射的端口

**Comment by tangtaoit** [comment]
30005端口是否对外开放， 如果开放了 查看下WuKongIM服务端的日志是报的什么错误

**Comment by xxd296008** [comment]
问题找到了，是我们k8s集群的问题，配置式对的，期待我们的悟空IM之旅
