### ISSUE TITLE
Uncaught SyntaxError: await is only valid in async functions and the top level bodies of modules

### ISSUE THREAD

**Issue by kangsange** [WuKongIM/WuKongIM#70]
报错：
Uncaught SyntaxError: await is only valid in async functions and the top level bodies of modules at home.html:85

代码是这么写的

![image](https://github.com/WuKongIM/WuKongIM/assets/37733022/8a4ecd27-54f4-46bb-84d8-1f7c34de2e2c)

**Comment by tangtaoit** [comment]
你这是普通的js吧 普通的promise应该是then和callback方法

**Comment by kangsange** [comment]
`{"header":{"no_persist":0,"red_dot":1,"sync_once":0},"setting":0,"message_id":1733771559308361700,"message_idstr":"1733771559308361728","client_msg_no":"191a216b0d3b419b8ba2f5f6f698f8130","message_seq":1,"from_uid":"u10002","channel_id":"u10001","channel_type":1,"expire":0,"timestamp":1702198326,"payload":"5L2g5piv6YKj5L2N77yf"}`



请问下最近会话列表获取到之后如上面的代码，怎么解析payload呢？

**Comment by kangsange** [comment]
或者说怎么解析出发送的聊天内容呢？

**Comment by tangtaoit** [comment]
Base64解码

**Comment by kangsange** [comment]
已解决
