### ISSUE TITLE
getChannel is error","error":"EOF"

### ISSUE THREAD

**Issue by kangsange** [WuKongIM/WuKongIM#71]
【Processor】getChannel is error","error":"EOF","fakeChannelID":"u10002@u10001","channelType":1}

发送用户消息代码如下：
const text = new wk.MessageText("hello") // 文本消息
const a = wk.WKSDK.shared().chatManager.send(text,new wk.Channel("u10001",wk.ChannelTypePerson))
console.log(JSON.stringify(a));  // 返回 {}

监听返回：
{"_packetType":4,"noPersist":false,"reddot":true,"syncOnce":false,"dup":false,"remainingLength":17,"messageID":"0","clientSeq":2,"messageSeq":0,"reasonCode":15}  // "reasonCode"  == 15

请问这是因为什么呢

**Comment by kangsange** [comment]
u10002和u10001 都已经调用后台api在IM系统里注册过了

**Comment by tangtaoit** [comment]
这个错误应该是你配置里打开了datasource，但是你业务没有实现datasource的相关接口，如果不需要datasource可以关闭他，如果需要按文档实现相关接口

**Comment by kangsange** [comment]
已解决
