### ISSUE TITLE
两人同时都在线，但聊天发送消息给对方时，发现IM都触发了 msg.offline 离线消息事件。

### ISSUE THREAD

**Issue by zhongaiping** [WuKongIM/WuKongIM#76]
日志如下：
   {"level":"debug","time":"2023-12-12 21:59:12","msg":"【DeliveryManager】Offline subscribers","offlineSubscribers":["1498604881472128"]}
{"level":"debug","time":"2023-12-12 21:59:12","msg":"【Webhook】webhook开始请求","eventURL":"https://xxx.top/applet/wkApi/wkBusinessEvent?event=msg.offline"}
{"level":"debug","time":"2023-12-12 21:59:12","msg":"【Webhook】webhook请求结束 耗时","mill":55}

**Comment by tangtaoit** [comment]
设计如此，只有用户主设备在线时才不会推送离线消息，主设备一般是APP，类似微信一样，Web聊天 APP一样可以收到离线消息，当然微信也可以设置不收，这样主动权在业务层，IM推离线，业务层可以根据用户的设置是否推送离线给用户APP。
