### ISSUE TITLE
发送消息和发送成功之间的关联

### ISSUE THREAD

**Issue by kangsange** [WuKongIM/WuKongIM#77]
1、编辑好内容，点击发送
2、返回发送成功或者失败

在这两步之间，怎么关联呢？
现在调用send方法返回为空{}，发送成功有client_msg_no,我想用户在点击发送那一刻就把消息放到发送框上面的板块，但处于发送中的状态，监听返回发送成功显示成功，失败显示失败，请问在上面两步之间如何关联呢？

**Comment by kangsange** [comment]
或者怎么才能在调用send的时候拿到client_msg_no呢？

**Comment by tangtaoit** [comment]
clientSeq关联，发送的时候会返回有clientSeq，监听到sendack的时候也有返回clientSeq

**Comment by kangsange** [comment]
目前发送的时候返回是一个空对象，里面啥都没有

**Comment by kangsange** [comment]
![aaa](https://github.com/WuKongIM/WuKongIM/assets/37733022/61376e8e-ddbc-4e4e-be1d-e3d02c93eec5)

**Comment by tangtaoit** [comment]
<img width="901" alt="image" src="https://github.com/WuKongIM/WuKongIM/assets/3895878/da6b75a6-2ce4-42bc-9d83-8b61711a73cf">
这个不就是吗？

**Comment by kangsange** [comment]
上面你圈的第一个是WKSDK.shared().chatManager.addMessageListener的返回，第二个是调用send方法后的回调

**Comment by tangtaoit** [comment]
我看了代码是返回的Promose<Message>对象 原生JS里 应该是.then去获取吧 你可以试试。

**Comment by tangtaoit** [comment]
不过你可以参考demo，不需要在send的时候获取clientSeq，可以在WKSDK.shared().chatManager.addMessageListener的时候渲染到UI，然后等ack的时候 再修改UI的发送状态  

https://github.com/WuKongIM/WuKongIMJSSDK/blob/main/examples/src/view/Chat.vue

**Comment by kangsange** [comment]
OK了。拿到回调了，只要有这个回调，那整个就能连起来了。
感谢！
