### ISSUE TITLE
关于删除频道和频道内拉黑某人的两个问题

### ISSUE THREAD

**Issue by zhongaiping** [WuKongIM/WuKongIM#78]
1 /channel/delete 删除频道 IM日志显示删除成功，但拉取会话列表 /conversation/sync依然能返回该频道
2  /channel/blacklist_add 频道内拉黑某人  IM日志显示 提示拉黑人的Id和频道ID 的hashcode一致，不能拉黑，这个要怎么处理 。谢谢

**Comment by tangtaoit** [comment]
1. 删除频道只是频道被销毁了，别人不能在里面发消息了，但是最近会话的记录还在，你需要删除最近会话记录 /conversations/delete
2. hashcode一致说明你被拉黑的人和拉黑的人传的uid是一样的，比如A要拉黑B，应该channel_id是A的uid，uids里包含B的uid
