### ISSUE TITLE
最近会话返回action的含义

### ISSUE THREAD

**Issue by kangsange** [WuKongIM/WuKongIM#79]
WKSDK.shared().conversationManager.addConversationListener家庭返回里面，官方文档是这样写的；
![image](https://github.com/WuKongIM/WuKongIM/assets/37733022/6de7bd0e-0c6b-4ee8-978b-c12798fc755c)

请问下：
新增最近会话的意思是不是最近会话里面没有对方的最近会话但对方第一次给我发消息，我在最近会话列表里新增一个？
更新最近会话是已经存在我的最近会话列表里了，但对方给我发了新消息，我需要在最近列表里更新一下最新消息呢?
删除最近会话是已经存在但删除了对方在我的最近会话里面的数据呢？

**Comment by kangsange** [comment]
疑问就是哪类消息返回是更新，哪类消息返回的是新增，哪类返回的消息是删除呢？

**Comment by tangtaoit** [comment]
> WKSDK.shared().conversationManager.addConversationListener家庭返回里面，官方文档是这样写的； ![image](https://private-user-images.githubusercontent.com/37733022/290432400-6de7bd0e-0c6b-4ee8-978b-c12798fc755c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDg3ODksIm5iZiI6MTcwMjU0ODQ4OSwicGF0aCI6Ii8zNzczMzAyMi8yOTA0MzI0MDAtNmRlN2JkMGUtMGM2Yi00ZWU4LTk3OGItYzEyNzk4ZmM3NTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDEwMDgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MjlmNjdhMjJmYTlkYWEzZjNlZThjOTE1NTA0NGU1NTI5YTdiYjA3MzU4YjVlYWU0NjczYzU1ZjA2NjY0MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qWseyXwV-SrJo3DPgViaOywgRBW9hfypRQtbSZXEzHY)
> 
> 请问下： 新增最近会话的意思是不是最近会话里面没有对方的最近会话但对方第一次给我发消息，我在最近会话列表里新增一个？ 更新最近会话是已经存在我的最近会话列表里了，但对方给我发了新消息，我需要在最近列表里更新一下最新消息呢? 删除最近会话是已经存在但删除了对方在我的最近会话里面的数据呢？

你这里理解是正确的，当你会话列表里没有当前这个会话的时候 就是add，当你当前会话里有这个会话就是update。

比如A给B发了一条消息，假设A是第一次给B发消息，那肯定B的会话列表里没有A，当B收到消息的时候对于B来说A得会话就是add，以后收到A的消息B列表里的A会话都是update

**Comment by kangsange** [comment]
那现在的sdk有问题，经过我几十次清空/root/wukongim/data的测试来看，0和1出现的规律是无序的

**Comment by kangsange** [comment]
如果你确定我理解是正确的话，那我就可能在最近会话列表哪里的处理错误了。
最近会话列表的获取一定是在WKSDK.shared().config.provider.syncConversationsCallback里面去请求最近会话列表接口拿到数据吗？
是否可以直接通过接口拿到数据，自行用base64解密？

**Comment by kangsange** [comment]
> > WKSDK.shared().conversationManager.addConversationListener家庭返回里面，官方文档是这样写的； ![image](https://private-user-images.githubusercontent.com/37733022/290432400-6de7bd0e-0c6b-4ee8-978b-c12798fc755c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDg3ODksIm5iZiI6MTcwMjU0ODQ4OSwicGF0aCI6Ii8zNzczMzAyMi8yOTA0MzI0MDAtNmRlN2JkMGUtMGM2Yi00ZWU4LTk3OGItYzEyNzk4ZmM3NTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDEwMDgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MjlmNjdhMjJmYTlkYWEzZjNlZThjOTE1NTA0NGU1NTI5YTdiYjA3MzU4YjVlYWU0NjczYzU1ZjA2NjY0MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qWseyXwV-SrJo3DPgViaOywgRBW9hfypRQtbSZXEzHY)
> > 请问下： 新增最近会话的意思是不是最近会话里面没有对方的最近会话但对方第一次给我发消息，我在最近会话列表里新增一个？ 更新最近会话是已经存在我的最近会话列表里了，但对方给我发了新消息，我需要在最近列表里更新一下最新消息呢? 删除最近会话是已经存在但删除了对方在我的最近会话里面的数据呢？
> 
> 你这里理解是正确的，当你会话列表里没有当前这个会话的时候 就是add，当你当前会话里有这个会话就是update。
> 
> 比如A给B发了一条消息，假设A是第一次给B发消息，那肯定B的会话列表里没有A，当B收到消息的时候对于B来说A得会话就是add，以后收到A的消息B列表里的A会话都是update

应该是最近会话的数据源出了问题，请明示一下最近会话的数据源该怎么设置，万分感谢/。

**Comment by tangtaoit** [comment]
看这里的例子：https://github.com/WuKongIM/WuKongIMJSSDK/blob/main/examples/src/services/datasource.ts
