### ISSUE TITLE
现在消息是通过什么保存的

### ISSUE THREAD

**Issue by long0419** [WuKongIM/WuKongIM#8]
现在消息是通过什么保存的

**Comment by tangtaoit** [comment]
按频道保存在磁盘里，顺序读写，类似kafka，无需关系这层，消息都会异步通过webhook的形式通知到业务层，业务可以根据情况是否保存下来，后面用于做业务分析

**Comment by long0419** [comment]
请问现在历史消息 是保存下来了吗？

**Comment by tangtaoit** [comment]
保存了
