### ISSUE TITLE
syncConversationsCallback的话应该怎么写

### ISSUE THREAD

**Issue by kangsange** [WuKongIM/WuKongIM#80]
`wk.WKSDK.shared().config.provider.syncConversationsCallback = async Conversation => {
      let conversations = await _this.getFinallyConversationListHistoryApi();
      return conversations
  };`

_this.getFinallyConversationListHistoryApi() 是通过接口返回最近会话列表的数据

原本以为可以直接通过接口调用IM的最近会话就可以，但发现其他相关接口几乎都没法正确返回数据了，推来推去认为应该是最近会话列表的数据源的问题。

请问在js里面WKSDK.shared().config.provider.syncConversationsCallback  到底应该怎么调用，demo看了还是没看出来怎么写的，请问一下到底该怎么写，希望写过的人提供一个demo，非常感谢！！！

**Comment by tangtaoit** [comment]
因为你用的原生的JS写法，这里主要的问题是await和sync怎么转换为原生的写法，我看了JSSDK里的编译后的browser的源码他是把await和sync 转换为__awaiter 和__generator方法了，参考 
<img width="828" alt="image" src="https://github.com/WuKongIM/WuKongIM/assets/3895878/46808813-250d-4557-920b-4a209fb4c2a8">

还有一种做法就是不要sdk管理最近会话，自己去调用接口获取最近会话，然后收到消息自己维护最近会话的变化，参考代码： https://github.com/WuKongIM/WuKongIMJSSDK/blob/main/src/conversation_manager.ts
