### ISSUE TITLE
断网后发送信息，然后再重新链接网络，最近会话的记录消息是断网前的那条

### ISSUE THREAD

**Issue by tiziyt** [WuKongIM/WuKongIM#81]
我这边断网后发送信息，然后再重新链接网络，最近会话的记录消息是断网前的那条是为什么呢，得刷新页面后才可以获取到最新的

**Comment by tangtaoit** [comment]
同步最近会话写到 连接成功的事件里

参考： https://github.com/TangSengDaoDao/TangSengDaoDaoWeb/blob/main/packages/tsdaodaobase/src/Pages/Chat/vm.ts#L67

**Comment by tiziyt** [comment]
const connectStatusListener = async (status) => {
  if (status === ConnectStatus.Connected) {
    const remoteConversations = await WKSDK.shared().conversationManager.sync() // 同步最近会话列表
    if (remoteConversations && remoteConversations.length > 0) {
      conversationWraps.value = sortConversations(remoteConversations.map(conversation => new ConversationWrap(conversation)))
    } 
 }
} 我是这样写在连接成功的事件里的,还是不可以呢.

**Comment by tangtaoit** [comment]
你试试我们的demo有这个问题吗
