### ISSUE TITLE
文本(带回复)里面的根消息的message_id字段root_mid是什么含义？

### ISSUE THREAD

**Issue by kangsange** [WuKongIM/WuKongIM#83]
![image](https://github.com/WuKongIM/WuKongIM/assets/37733022/1d3c5868-cbeb-499b-a52c-b104b7629cd1)

**Comment by tangtaoit** [comment]
这个是一个业务属性，比如C回复了B回复A的一条消息，那么message_id是B消息的ID，root_mid就是A消息的ID，这个需要视你自己的业务情况来定，root_mid不是必须的

**Comment by kangsange** [comment]
![image](https://github.com/WuKongIM/WuKongIM/assets/37733022/045ed651-54aa-45de-8c5c-e325d37e9970)


这个协议好像无效，测试很多次，在发送方可以看到数据，但是在接受方，reply为空

**Comment by tangtaoit** [comment]
发送的代码看一下。

**Comment by kangsange** [comment]
![image](https://github.com/WuKongIM/WuKongIM/assets/37733022/95a1a53c-3374-4851-9238-860a8a76409e)

**Comment by tangtaoit** [comment]
不是这样发的， reply是一个对象，参考： https://github.com/TangSengDaoDao/TangSengDaoDaoWeb/blob/main/packages/tsdaodaobase/src/Components/Conversation/index.tsx#L581C24-L581C24

**Comment by kangsange** [comment]
![image](https://github.com/WuKongIM/WuKongIM/assets/37733022/67246449-b3bb-440e-b539-566567d79cbb)
还是bu不行，A发送给B，在B这里是正常的，但是在B收到消息后，如下：
![image](https://github.com/WuKongIM/WuKongIM/assets/37733022/2d3d9fd6-a4af-47aa-99a2-2859e15bcf32)


就是空的了

**Comment by tangtaoit** [comment]
建议使用typescript
