### ISSUE TITLE
 有个问题请教一下，用户最近会话的列表处理逻辑，先通过api获取悟空im的会话消息，然后再根据用户id遍历mysql的user 头像以及昵称基础信息，再组成新数组渲染数据吗

### ISSUE THREAD

**Issue by jkguo-looker** [WuKongIM/WuKongIM#84]

**Comment by tangtaoit** [comment]
参考： https://github.com/WuKongIM/WuKongIM/issues/21

整体流程：

1. APP添加channelInfo信息的监听
2.调用SDK的fetchChannelInfo触发sdk去请求channelInfo的数据源从而请求第三方自己的业务服务器获取的数据塞到channelInfo里
3. APP监听到channelInfo信息，去重新渲染UI，此时UI通过getChannelInfo就能拿到channelInfo信息

参考： https://github.com/WuKongIM/WuKongIMJSSDK/blob/main/examples/src/components/Conversation/index.vue#L129C3-L129C3
