### ISSUE TITLE
如何更好的删除消息以及撤回消息的处理

### ISSUE THREAD

**Issue by snamper** [WuKongIM/WuKongIM#86]
这个需要看看是不是底层也可以解决

最好消息里增加可以变更的状态，不用从业务端取， 在输出的时候可以直接去掉

业务端存的数据多了比较费劲  

找回：给指令同步 扩展字段，撤回状态就在扩展字段内

但实际后期拉取也会 需要一个删除状态 ，这个状态最好可以自定义可以扩展2到3个字段可以扩展其他 状态，不清楚是否现在这种存储是否适合

**Comment by tangtaoit** [comment]
因为存储成本很低，目前删除都是假删除，底层暂时不会支持真正删除，这涉及到消息序号连续问题，如果真正删除了，消息序号将不会连续。假删除 业务端就可以实现，这样可控性更强。后续再看是否有必要实现真正的删除。
