### ISSUE TITLE
频道消息如何查询未读

### ISSUE THREAD

**Issue by superlbr** [WuKongIM/WuKongIM#88]
`POST /channel/messagesync` 接口里没有unread？

**Comment by tangtaoit** [comment]
你说的unread是红点 还是 消息已读未读？，如果是红点 在 /conversation/sync接口里有unread字段，如果是消息的已读和未读这个是业务属性，需要你自己业务端去实现。

**Comment by superlbr** [comment]
好吧。简易的已读未读，取/conversation/sync接口，还需要遍历找到对应channel

**Comment by tangtaoit** [comment]
> 好吧。简易的已读未读，取/conversation/sync接口，还需要遍历找到对应channel

这个完全可以业务端实现,参考：https://github.com/TangSengDaoDao/TangSengDaoDaoServer/blob/main/modules/message/api.go#L304
