### ISSUE TITLE
关于消息重发机制

### ISSUE THREAD

**Issue by doralines** [WuKongIM/WuKongIM#94]
之前用过别家的开源IM，很多我都发现一个问题，那就是消息重发的问题。
当用户网络状态特别差的情况会出现，假设用户A在高铁上，这个时候网络会特别差， A用户给B发消息，A用户端显示只有一条消息，但是B用户端会显示收到了2条相同的消息，消息ID也不同，并且时间间隔在几秒甚至十几秒内。
不知道wukongIm是否会存在这个问题？

**Comment by tangtaoit** [comment]
重试分两种情况：
1. 客户端发送消息没有收到服务端的响应（sendack）那么客户端会不断重试发送同一条消息。
2. 服务端投递消息给客户端后，没有收到客户端的响应（recvack）服务端会不断重试给客户端发送消息

这两种情况都会因为客户端的网络不稳定 导致消息重复。

WuKongIM的解决方案：

1. 第一种情况，WuKongIM的sdk发送消息的时候都会为消息生成一个uuid的clientMsgNo唯一字符串，重试的消息clientMsgNo不会变。所以接收者会收到2条这个消息 但是clientMsgNo是一样的，接受者虽然重复收到了多条，但是只消息clientMsgNo相同的一条。所以在用户体验上 用户并感觉不到消息重复的事件。
2. 第二种情况，服务端重试消息的时候不会改变clientMsgNo和messageID所以相同的原理客户端根据clientMsgNo去重即可
