### ISSUE TITLE
最近会话保存时间的配置

### ISSUE THREAD

**Issue by doralines** [WuKongIM/WuKongIM#95]
悟空IM 配置文件中有关于最近会话保存时间的配置，是不是用户超过这个过期时间没有上线 最近会话会自动删除，上线后什么都收不到？

**Comment by tangtaoit** [comment]
<img width="824" alt="image" src="https://github.com/WuKongIM/WuKongIM/assets/3895878/f46b9963-f2d4-4d16-84ca-cb8827e8c4db">
那个时间？

cacheExpire: 这里指清除内存里的最近会话缓存，并不表示清除最近会话
syncInterval: 是最近会话保存到磁盘的时间（就算最近会话丢失，会根据客户端的会重构出来，除非客户端也没有这个最近会话，服务端也没有，这种情况最近会话可能就丢了，需要这个会话再有消息的时候，才会重新构建出来，所以这个错误是可以容忍的）

userMaxCount：这个是一个用户最大保存他的最近会话数量，比如保存1000个，如果又产生了一个新的会话，这个最新的会话，会挤掉最老的一个会话 类似lru算法。被挤掉的老会话如果有新消息就又会出现在列表里。所以1000个我认为已经足够了，毕竟很少有人 在很短的时间内同时跟1000个人聊天，就算同时跟1000个人聊天 应该也不会再关心1000后的内容

**Comment by doralines** [comment]
> <img alt="image" width="824" src="https://private-user-images.githubusercontent.com/3895878/297963986-f46b9963-f2d4-4d16-84ca-cb8827e8c4db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDM0NzcsIm5iZiI6MTcwNTY0MzE3NywicGF0aCI6Ii8zODk1ODc4LzI5Nzk2Mzk4Ni1mNDZiOTk2My1mMmQ0LTRkMTYtODRjYS1jYjg4MjdlOGM0ZGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTlUMDU0NjE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGJmYzAxMGNlNmViMGVlMTY4MGRkZjQzYzI5M2I3ZmUwN2FlZmUxNzNlYzY5NDZiYjZmM2MxMWZjYWY0Y2FkOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NWoJJr2UWXzbsb5imNHTD4GwgQpRHHgICCNTw_mQbO0"> 那个时间？
> cacheExpire: 这里指清除内存里的最近会话缓存，并不表示清除最近会话 syncInterval: 是最近会话保存到磁盘的时间（就算最近会话丢失，会根据客户端的会重构出来，除非客户端也没有这个最近会话，服务端也没有，这种情况最近会话可能就丢了，需要这个会话再有消息的时候，才会重新构建出来，所以这个错误是可以容忍的）
> 
> userMaxCount：这个是一个用户最大保存他的最近会话数量，比如保存1000个，如果又产生了一个新的会话，这个最新的会话，会挤掉最老的一个会话 类似lru算法。被挤掉的老会话如果有新消息就又会出现在列表里。所以1000个我认为已经足够了，毕竟很少有人 在很短的时间内同时跟1000个人聊天，就算同时跟1000个人聊天 应该也不会再关心1000后的内容

syncOnce就是单个会话中的未读消息数量，是这个意思吗？

**Comment by tangtaoit** [comment]
> > <img alt="image" width="824" src="https://private-user-images.githubusercontent.com/3895878/297963986-f46b9963-f2d4-4d16-84ca-cb8827e8c4db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDM0NzcsIm5iZiI6MTcwNTY0MzE3NywicGF0aCI6Ii8zODk1ODc4LzI5Nzk2Mzk4Ni1mNDZiOTk2My1mMmQ0LTRkMTYtODRjYS1jYjg4MjdlOGM0ZGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTlUMDU0NjE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGJmYzAxMGNlNmViMGVlMTY4MGRkZjQzYzI5M2I3ZmUwN2FlZmUxNzNlYzY5NDZiYjZmM2MxMWZjYWY0Y2FkOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NWoJJr2UWXzbsb5imNHTD4GwgQpRHHgICCNTw_mQbO0"> 那个时间？
> > cacheExpire: 这里指清除内存里的最近会话缓存，并不表示清除最近会话 syncInterval: 是最近会话保存到磁盘的时间（就算最近会话丢失，会根据客户端的会重构出来，除非客户端也没有这个最近会话，服务端也没有，这种情况最近会话可能就丢了，需要这个会话再有消息的时候，才会重新构建出来，所以这个错误是可以容忍的）
> > userMaxCount：这个是一个用户最大保存他的最近会话数量，比如保存1000个，如果又产生了一个新的会话，这个最新的会话，会挤掉最老的一个会话 类似lru算法。被挤掉的老会话如果有新消息就又会出现在列表里。所以1000个我认为已经足够了，毕竟很少有人 在很短的时间内同时跟1000个人聊天，就算同时跟1000个人聊天 应该也不会再关心1000后的内容
> 
> syncOnce就是单个会话中的未读消息数量，是这个意思吗？

不是的，这个是服务刷盘最近会话到磁盘的机制，如果用户有syncOnce的数量的最近会话发生了变化就立马保存到磁盘。
