### ISSUE TITLE
cmd是什么？和普通的message有什么区别吗

### ISSUE THREAD

**Issue by doralines** [WuKongIM/WuKongIM#96]
看悟空IM官网中，频繁出现一个cmd的字眼，我想问一下 cmd消息和普通的消息有什么区别吗？

**Comment by a983132370** [comment]
我也想问下 cmd消息是否也是必达的，能不能实现只有用户在线的时候到达，离线丢弃

**Comment by tangtaoit** [comment]
cmd消息：不需要显示在用户聊天内的消息，cmd也就是指令，是服务器发送一些指令，然后app默认在后台执行指令对应的逻辑，比如：群成员数量更新了，其他群成员需要同步，那么服务器可以向群成员发送一个 {type:99,cmd:"groupMemberUpdate","channel_id":"xxx","channel_type":2} 的指令 群成员收到了 就会去服务器同步群成员数量到本地。像这种消息就是cmd消息，这消息并不需要显示出来给用户看。

普通消息： 普通消息就是聊天，通知类的，一句话就是：用户可以看见的消息

**Comment by tangtaoit** [comment]
> 我也想问下 cmd消息是否也是必达的，能不能实现只有用户在线的时候到达，离线丢弃

可以的 消息头的 no_persist=1 就是不存储，不存储就不会有离线消息。
