### ISSUE TITLE
sdk本地存储大量消息是否会造成客户端卡顿

### ISSUE THREAD

**Issue by doralines** [WuKongIM/WuKongIM#97]
本地sdk保存的消息 会不会在本地消息存储量特别大的情况下，导致客户端变的卡顿（之前用过其他开源IM，他们的sdk在本地消息存储上十万后 整个App都会变得特别卡）

**Comment by doralines** [comment]
还有就是 是否支持统计本地消息大小，然后清理

**Comment by tangtaoit** [comment]
> 本地sdk保存的消息 会不会在本地消息存储量特别大的情况下，导致客户端变的卡顿（之前用过其他开源IM，他们的sdk在本地消息存储上十万后 整个App都会变得特别卡）

WuKongIM消息是懒加载机制，就算你本地数据库里的消息全清除了，也不影响用户的正常使用，因为当用户需要看那些消息的时候，sdk会先取本地，本地没有 就会去服务器拉取合并到本地。

你可以体验下唐僧叨叨app，你聊了许多消息，然后app卸载再重新安装，消息1秒内都不需要就能恢复。

**Comment by tangtaoit** [comment]
> 还有就是 是否支持统计本地消息大小，然后清理

本地消息主要是文件，文字的大小基本可以忽略，sdk会将文件下载下来按频道进行分类，只需要统计这些文件夹下的文件大小即可

**Comment by doralines** [comment]
> > 本地sdk保存的消息 会不会在本地消息存储量特别大的情况下，导致客户端变的卡顿（之前用过其他开源IM，他们的sdk在本地消息存储上十万后 整个App都会变得特别卡）
> 
> WuKongIM消息是懒加载机制，就算你本地数据库里的消息全清除了，也不影响用户的正常使用，因为当用户需要看那些消息的时候，sdk会先取本地，本地没有 就会去服务器拉取合并到本地。
> 
> 你可以体验下唐僧叨叨app，你聊了许多消息，然后app卸载再重新安装，消息1秒内都不需要就能恢复。

嗯 本地文件如果存储过多，会影响App的运行速度吗？

**Comment by tangtaoit** [comment]
> > > 本地sdk保存的消息 会不会在本地消息存储量特别大的情况下，导致客户端变的卡顿（之前用过其他开源IM，他们的sdk在本地消息存储上十万后 整个App都会变得特别卡）
> > 
> > 
> > WuKongIM消息是懒加载机制，就算你本地数据库里的消息全清除了，也不影响用户的正常使用，因为当用户需要看那些消息的时候，sdk会先取本地，本地没有 就会去服务器拉取合并到本地。
> > 你可以体验下唐僧叨叨app，你聊了许多消息，然后app卸载再重新安装，消息1秒内都不需要就能恢复。
> 
> 嗯 本地文件如果存储过多，会影响App的运行速度吗？

消息是存在sqlite db里的 过多消息肯定是有点影响的，但是一个用户10几年的消息也很难让sqlite db变的很慢吧

**Comment by doralines** [comment]
> > > > 本地sdk保存的消息 会不会在本地消息存储量特别大的情况下，导致客户端变的卡顿（之前用过其他开源IM，他们的sdk在本地消息存储上十万后 整个App都会变得特别卡）
> > > 
> > > 
> > > WuKongIM消息是懒加载机制，就算你本地数据库里的消息全清除了，也不影响用户的正常使用，因为当用户需要看那些消息的时候，sdk会先取本地，本地没有 就会去服务器拉取合并到本地。
> > > 你可以体验下唐僧叨叨app，你聊了许多消息，然后app卸载再重新安装，消息1秒内都不需要就能恢复。
> > 
> > 
> > 嗯 本地文件如果存储过多，会影响App的运行速度吗？
> 
> 消息是存在sqlite db里的 过多消息肯定是有点影响的，但是一个用户10几年的消息也很难让sqlite db变的很慢吧

可以考虑SDK加一下清理本地消息的接口，数据多了真的会变很慢，整个app都会延迟很大...像一些用户比较多的群，一天都有上万条消息。不到几天就占满了

**Comment by tangtaoit** [comment]
> > > > > 本地sdk保存的消息 会不会在本地消息存储量特别大的情况下，导致客户端变的卡顿（之前用过其他开源IM，他们的sdk在本地消息存储上十万后 整个App都会变得特别卡）
> > > > 
> > > > 
> > > > WuKongIM消息是懒加载机制，就算你本地数据库里的消息全清除了，也不影响用户的正常使用，因为当用户需要看那些消息的时候，sdk会先取本地，本地没有 就会去服务器拉取合并到本地。
> > > > 你可以体验下唐僧叨叨app，你聊了许多消息，然后app卸载再重新安装，消息1秒内都不需要就能恢复。
> > > 
> > > 
> > > 嗯 本地文件如果存储过多，会影响App的运行速度吗？
> > 
> > 
> > 消息是存在sqlite db里的 过多消息肯定是有点影响的，但是一个用户10几年的消息也很难让sqlite db变的很慢吧
> 
> 可以考虑SDK加一下清理本地消息的接口，数据多了真的会变很慢，整个app都会延迟很大...像一些用户比较多的群，一天都有上万条消息。不到几天就占满了

sdk有这种接口
