### ISSUE TITLE
userMsgQueueMaxSize 的配置

### ISSUE THREAD

**Issue by doralines** [WuKongIM/WuKongIM#98]
userMsgQueueMaxSize: 0 #  用户消息队列最大大小，超过此大小此用户将被限速，0为不限制  这一个配置不是很懂

**Comment by tangtaoit** [comment]
客户端发送消息，服务端收到消息后 是放到用户的队列里，然后服务器再处理，如果这个队列超过了这个配置，服务器就不会再接受用户的消息。
