### ISSUE TITLE
云端数据怎么清理

### ISSUE THREAD

**Issue by doralines** [WuKongIM/WuKongIM#99]
云端数据太多的情况下 怎么按需清理XX天前的数据

**Comment by tangtaoit** [comment]
WuKongIM是读扩散 就算1万人的群，发一条消息也只会保存1条消息，加上WuKongIM自研的消息db（消息格式采用的紧凑性的格式） 加上现在磁盘很廉价，所以WuKongIM暂时还没有清理消息的接口。因为这个需求暂时不迫切。

（1T硬盘大概可以存 20-30亿条消息）
